---
title: "Exploratory Data Analysis"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

# Rationale

Important for understanding data, checking for data issues/errors, checking assumptions for different statistical models.

LOOK AT YOUR DATA—most overlooked step in data analysis!

# Descriptive statistics

## Sample

- N—expected?
- Extent of missingness

## Distribution

- Frequencies

## Central Tendency

- Mean
- Median
- Mode

## Dispersion

- Standard deviation
- Observed minimum and maximum (vis-à-vis possible minimum and maximum)
- Skewness
- Kurtosis

## Plots

See [here](analysis-figures.html) for resources for creating figures in R.

- Histogram
- Density plot
- Box and whisker plot
- Violin plot

# Basic inferential statistics

## Statistical decision tree

## Tests of systematic missingness (i.e., whether missingness on a variable depends on other variables)

- Generally test:
    - Whether outcome variable(s) differ as a function of any model variables (predictors and covariates) and as a function of any key demographic characteristics (sex, ethnicity, SES)
    - Whether focal predictor variable(s) differ as a function of any model variables (including outcome variable) and as a function of any key demographic characteristics
- For instance:
    - Whether males are more likely than girls to be missing EEG scores
    - Whether longitudinal attrition is greater in lower SES families
- If missingness differs systematically as a function of other variables, can include that variable as a control variable in models, and/or can include that variable in multiple imputation to inform imputed scores for missing values

## Correlation matrices
