---
title: "Git, GitLab, and GitHub"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

GitLab (access via GitHub desktop app)

- Download GitHub Desktop App (https://desktop.github.com/)
- Create an account on UI GitLab Enterprise (https://research-git.uiowa.edu/)
- Have Dr. Petersen add you to Petersen Lab GitLab group

# Why Important

- Provides backups of all files in the cloud
- Can access the files in the cloud from any computer with access to the internet, even if you are away from your local computer
- Version control: Provides history of all (committed) changes made to all files
- If you make a mistake in your code, you can easily revert to a prior version because you took snapshots (commits) of your files!
    - Allows you to write cleaner code (you do not need to keep all the "commented out" lines of code)
    - No longer have to keep files or folders named "project_old" (or whatever)
- Keeps all files for project self-contained, helps increase reproducibility
- Allows easier collaboration with others on the project
- Allows easier sharing with outside researchers

# How to Use
- For more detailed instructions, see here:
    - https://research-git.uiowa.edu/PetersenLab/R-InitialSetup/-/blob/master/GitLab/GitLab%20Instructions.md
- Create a new repository (repo) whenever you start a new project
- Follow the Petersen Lab template for how to structure your repo (folder structure, .gitignore file, etc.):
    - https://research-git.uiowa.edu/PetersenLab/Template
- To collaborate with others:
    - Navigate to the repo on the UI GitLab website
    - When in the repo, click "Members"
    - Add the Collaborator
- Each time you want to work on the files in the repo, follow this cycle:
    1. Using the GitHub Desktop app, sync the repo files from the cloud to the repo on your local computer
    1. Do you work on the repo: make any code/file/folder additions, changes, or deletions
    1. Using the GitHub Desktop app, commit the changes
        - Use a separate "commit" for each separable "functional unit" changed
    1. Using the GitHub Desktop app, sync the repo files from your local computer to the repo on the cloud
        - Never leave file changes uncommitted or unsynced when you stop working on the repo for the day!
