---
title: "R"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

 > "*R will always be arcane to those who do not make a serious effort to learn it. It is not meant to be intuitive and easy for casual users to just plunge into. It is far too complex and powerful for that. But the rewards are great for serious data analysts who put in the effort.*"

— [Berton Gunter R-help August 2007](https://www.brodrigues.co/blog/2022-06-02-arcane/)

# Getting Started

- Download R: https://cran.r-project.org/
- Download RStudio: https://www.rstudio.com/products/rstudio/download/

Follow the initial setup steps:
https://research-git.uiowa.edu/PetersenLab/R-InitialSetup

For antialiased plots in `RStudio`, change the Graphics backend to `Cairo`:
Tools → Global Options → Graphics

- Verify that you can export data from REDCap using R script: `\\iowa.uiowa.edu\Shared\ResearchData\rdss_itpetersen\Lab\Studies\School Readiness Study\Data Processing\1. Export Data\Export Data.R`
- Clone "R-DataAnalysis" GitHub repo to your local machine: `https://research-git.uiowa.edu/PetersenLab/R-DataAnalysis`
    - Follow the Petersen Lab template for how to structure your repo (folder structure, `.gitignore` file, etc.): https://research-git.uiowa.edu/PetersenLab/Template

# Learning `R` {#learning}

## Base R

Here are a slew of resources for learning base `R` (in addition to the documents in the lab's [Primer Articles folder](https://drive.google.com/drive/u/0/folders/1U0pNrjF2_tIPU6BiyCv0HqbOUA5P516r)):

- Use this Intro to R: https://www.statmethods.net/
- I used this resource considerably when I was learning R
- Learn how to become a better coder: https://www.r-bloggers.com/10-top-tips-for-becoming-a-better-coder/
- How to become fluent in R: https://www.sharpsightlabs.com/blog/are-you-fluent-r/
- Video training courses in R skills: https://www.pluralsight.com/search?q=R
- Browse the Cookbook for R to find solutions to common tasks and problems: http://www.cookbook-r.com/
- Free Codeacademy course on R: https://www.codecademy.com/learn/learn-r
- Free Coursera courses on R: https://pairach.com/2012/12/22/learn-to-use-r-for-free-with-coursera/
- MOOCs and courses to learn R: https://www.r-bloggers.com/moocs-and-courses-to-learn-r/
- Watch these videos from Coursera: http://blog.revolutionanalytics.com/2012/12/coursera-videos.html
- RStudio Webinars: https://www.rstudio.com/resources/webinars/
- Check out these resources for getting started with R: https://stats.idre.ucla.edu/r/
- Take this Introduction to R course: https://www.datacamp.com/courses/free-introduction-to-r
- Learn R interactively with swirl: https://swirlstats.com/
- Use the learnr package: https://blog.rstudio.com/2017/07/11/introducing-learnr/
- You’ll sometimes find relevant articles on R-bloggers: https://www.r-bloggers.com/

## Statistics (using `R`)

The following are resources for learning statistics using `R`.

Free textbook on Learning Statistics with R: https://learningstatisticswithr.com

An excellent introductory textbook on Discovering Statistics using R: https://www.amazon.com/Discovering-Statistics-Using-Andy-Field/dp/1446200469

## `tidyverse`

The following are resources for learning `tidyverse`, which is a collection of R packages for data management:

https://www.tidyverse.org/learn/

https://www.linkedin.com/learning/learning-the-r-tidyverse/welcome?u=42459020

## Questions

If you have questions:

- Post to the R mailing list: https://stat.ethz.ch/mailman/listinfo/r-help
- Post to forums: https://stackoverflow.com/questions/tagged/r
- More info: https://www.r-bloggers.com/where-to-get-help-with-your-r-question/


# Style Guide

## Use R Notebooks for "Computational Notebooks"

Using R Notebooks for "Computational Notebooks" is helpful for reproducible code that can be shared with others.
See links below for more info about how to create R Notebooks:

- https://garrettgman.github.io/rmarkdown/r_notebooks
- https://bookdown.org/yihui/rmarkdown/notebook.html

## Separate sections in code

- In R scripts, use sections.
    - To insert a section in Rstudio, use CTRL-Shift-R or "Code" - "Insert Section"
- In R Notebooks/Markdown, use Headers and code chunks.
    - Headers: 1, 2, or 3 pound signs
    - Code Chunks: Ctrl+Alt+I; or click "Insert" button then "R"
- Variable names
    - Use meaningful variable names; we want to know what a variable represents without having to consult an external codebook for every variable
    - Variable names should include the prefix for the measure followed by an underscore
        - e.g., `cbcl_` for the Child Behavior Checklist variables
    - Use lower camel case for variable naming
        - e.g., `prefix_thisIsTheVariableName`
- Comment code frequently and clearly!
    - You want you (and others) to easily be able to understand your code if you come back to it several years later!

# Data Management

Tidyverse: https://www.tidyverse.org

University of Iowa Workshops

# Saving Plots

`png(); dev.off()`

# Saving Output

R Markdown

- https://rmarkdown.rstudio.com/lesson-1.html
- https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf
- https://bookdown.org/yihui/rmarkdown/

# Shortcuts

- Run selected line(s) of code: Ctrl + Enter
- Comment/uncomment code: Ctrl + Shift + C
- Pipe: Ctrl + Shift + M
- Insert Code Chunk: Ctrl + Alt + I
- Assignment operator: Alt + - (alt-dash)
- Select multiple lines: Ctrl + Alt, up or down; or Alt + drag mouse
- Search: Ctrl + Shift + F
- Show all keyboard shortcuts: Alt + Shift + K
