---
title: "Lab Expectations for Graduate Students"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

Please read the whole document of lab expectations[^1] carefully.
If you have questions or concerns, please talk with me about them; the document, like my research style, is a work in progress.
I hope this document conveys the care and thoughtfulness I bring to the work we do together.
I review this document periodically to make sure that my expectations and obligations are clear and that nothing important is forgotten.

# The broad goals of my research program

As part of my job as a professor, I am expected to write grants and initiate research that will make tangible contributions to science, the academic community, and to society.
You will be helping me carry out—and improve—this research.
Along the way, the goal is that you will develop an independent research program.
It is imperative that we implement strong scientific methods, and conduct ourselves in an ethical way.
Dissemination of the knowledge we gain is critical to the advancement of our field.
Thus, a primary goal of our work is publishing our findings in scientific journals.

# The broad goals of mentoring

The goals of mentoring in this lab are for each trainee *to receive theoretical and technical training, to work productively on interesting research projects, and to best prepare themselves for their future career*.
Thus, a major emphasis of your work will be data analysis, writing, and publishing papers in strong journals.
Here I list some expectations to help you understand how the lab operates and how we can achieve these goals together.

# What trainees can expect of me

Here are what trainees can expect of me:

1. I will work tirelessly for the good of the lab group; the success of every member of our group is my top priority, no matter their personal strengths and weaknesses, or career goals.
1. I will set high standards for the lab group, including you, others, and myself.
1. I will provide you guidance and resources to conduct research projects we are both interested in.
1. I will help you navigate your graduate program of study.
1. I will lead by example and facilitate your training in complementary skills needed to be a successful scientist, such as oral and written communication skills, grant writing, lab management, mentoring, and scientific professionalism.
1. I will provide you guidance and resources for your career development.
1. I will reply promptly to the materials you send me (e.g., emails, drafts, and slides).
1. I will respect your time and work, and give you credit appropriately.
1. I will provide advice on other issues, if you choose to engage me.
1. I will be your advocate.

# What I expect of trainees

Here is what trainees I expect of trainees:

1. Maintain good progress on research and training-related activities
1. Conduct all research and training-related activities responsibly
1. Respect other lab members

I am ambitious and have high standards, and I expect the same from you.
Below are more detailed descriptions of the expectations:

## Research projects and training

Take advantage of your opportunity to work at a world-class university by developing and refining stellar scientific skills.
I expect that you will learn how to plan, design, and conduct high-quality scientific research.

I expect all trainees to maintain good progress on their projects.
This includes: keeping updated on the literature and research methods, actively thinking about the best ways to conduct your research projects and applying them, regularly discussing your research progress with me, following the plans based on our discussions, and presenting (conferences, presentations, and/or journal articles) the findings at a satisfactory level.
Writing is the single most important ability to develop during graduate school.
I expect you to write frequently, and I encourage you to write daily.
I encourage students to read Paul Silva's "[How to Write a Lot](https://www.amazon.com/How-Write-Lot-Practical-Productive/dp/1433829738)," and I am happy to lend the book to you.
I encourage you to use EndNote, Zotero, or another reference manager to manage your references and write the References section of papers.
Reference management software will save you lots of time.

My expectation is that you will be engaged in research activities beyond those required by the program.
Have multiple research projects to work on.
Having multiple ongoing projects provides important diversification—if a given project is not working out as expected, you have other projects you can turn to.
But focus and finish.
The "currency" in science is published papers—they drive a lot of what we do.
Because our lab is supported by taxpayer dollars, we have an obligation to complete and disseminate our findings.
I expect you to lead first-authored projects (in addition to any collaborative projects) and to publish your work in high-impact journals.
It is my policy that students are first-author on all work for which they lead the data analysis and writing.
I will push you to publish your research as you move through your training program, <ins>not</ins> only at the end.
I expect trainees to be lead author on at least two journal paper submissions, preferably three or four (or more!).
Productivity in terms of publishing high-quality papers and securing funding is crucial to be competitive for many jobs.

I expect you to apply for external funding—examples include the National Science Foundation Graduate Research Fellowship Program (NSF-GRFP) and the National Institutes of Health National Research Service Award (NIH NRSA).
I encourage students to submit a NSF-GRFP in their first semester.
I encourage students to submit a NIH NRSA in their second or third year.
Getting a first-authored publication in your first or second year is important for these (and other) fellowships and for awards.

For many jobs, presentation skills are also highly important, including skills in presenting research to broad audiences of scientists outside of your area.
For academic positions, while papers and grants "get your foot in the door" and help you get an interview, the "job talk" (typically to the whole Department) is the single most important criterion during a job interview—because that is the one thing that all faculty see.
Thus, I expect you to present your research frequently and in multiple outlets.
Challenge yourself by presenting your work at meetings and seminars as early as you can.
I also expect you to go to Departmental colloquia series by speakers who are outside of your area.

We will have meetings to discuss the research project(s) you find interesting that also advance the lab's interests.
I always welcome new ideas and project proposals, so please come to me if you want to discuss new projects.
A piece of advice that was given to me as a graduate student that I pass onto you is to find a question or problem that excites you and "date" it.
You'll know you've found an idea that truly excites you when you find yourself thinking about it while brushing your teeth, going for walks, etc.
Much of the important and exciting work in science happens at the ideas stage.

## Data and research materials

Confidentiality of data is paramount.
All hard-copy physical research data must remain in the lab.
All electronic data should be accessed from the lab, on university computers, or secure private computers.
Electronic data should not be accessed on public computers.
Identifiable electronic data should be stored only on the lab's RDSS share and should not be saved onto your computer.
When working from private spaces, the university VPN can be accessed to ensure a secure internet connection.

You are expected to maintain detailed, organized, and accurate laboratory records in a lab notebook.
Be aware that all tangible research data and related research materials are my property as the lab director.
When you leave the lab, I encourage you to retain access to the lab's research data via VPN to the lab drive (RDSS share).
One full set of all data must stay in the lab, with appropriate and accessible documentation.
Regularly back up the files on your computer using Microsoft OneDrive, which is provided by the university.
De-identified data and analysis scripts associated with projects should be saved in the project repository of the lab's GitLab page (https://research-git.uiowa.edu/PetersenLab), which is hosted by the university and approved by our IRB.

## Research ethics

You should respect all ethical standards—including compliance with all university, state, and federal regulations in addition to the APA Ethics Code—as they relate to responsible conduct in research, possible conflicts of interest, privacy and human subjects research, laboratory safety, authorship, peer-review guidelines, and data ownership, reporting, and sharing.
When ethical dilemmas or uncertainties arise, ask me and others for guidance.
Consult, consult, consult!

In this lab, we work hard to do the best science we can.
During the process, obstacles and frustrations are inevitable, and sometimes more common than you would imagine.
It is my hope that we will work together to tackle these challenges and to build up your resilience.
To this end, please keep me updated on your progress—both the good and bad.

Mistakes are inevitable and are part of your training, so do not feel bad about making mistakes—I make mistakes on a daily basis.
I strive for the lab to provide a supportive environment to ask questions and admit mistakes.
As your mentor, I am also responsible for your research and training.
So please do let me know if such things happen and we will work together to recover from them.
Usually the earlier you inform me, the less damage there will be.
Being frank about your mistakes will be greatly appreciated.
However, things like intentionally faking data and intentionally covering mistakes are unacceptable and will lead to severe consequences.

## Time in lab

I expect you to be at work and on campus during the workday: 9ish–5ish or 8ish–4ish.
In addition, I expect your availability to span 9–5 for scheduling meetings with me or members of the team—the same hours, generally, that the program attempts to schedule meetings.
During the workday, you are expected to work in the lab when you are not in class, teaching, or doing clinical work.
This is not about accountability—rather, it is to the benefit of you and the team.
Our approach is optimal for the type of projects we carry out: longitudinal projects such as ours are one big enterprise with many moving parts, all of which have to work together smoothly.
Each student's individual project is embedded in that larger umbrella (retaining each student's uniqueness, ideas, etc.).
Thus, the physical interactions for the whole team, in one space, with shared work ethic, are so important.
Part of your job is to be in the lab and talk with other people about your research.
We all benefit from having a group of people we can talk with about research questions and problems.
We have a collaborative lab environment.
Our lab works as a team, and other lab members count on you being there.
Likewise, you benefit from having other team members, myself, and Departmental staff available.
Working in the lab space helps improve quality control of lab procedures and can lead to exciting collaborative projects.
This short blurb on how "[Isolation is one of the biggest enemies of graduate students](https://www.insidehighered.com/views/2005/10/26/we-need-humanities-labs)" may give you some insight why facetime in the lab is so important:

> "I wonder how an English professor would feel spending a week in a physics lab.
> Not about the scientific work, but about the frequent, ongoing interaction between students and peers, post-docs and faculty.
> Scientists see each other in the lab, if not daily, then at least weekly.
> They have frequent lab meetings, colloquia and interaction with scholars at other universities around joint research.
> During my graduate training in psychology at McGill University, especially in the research lab at the Montreal Neurological Institute, I spent hours hanging around the post-docs.
> I learned at least as much from them as I did from my interactions with my professors.
> The expectation was that I would be at the lab 9 to 5 or more, every day.
> I saw my adviser every day." – Gina Hiatt

Of course, there are exceptions; if you are sick, stay home.
You do not need my permission to attend medical appointments during lab hours.
If you are unable to come into lab due to bad weather, just let me know and you should be available to be reach-able quickly, just as you would be if you were in lab.

Nevertheless, graduate school is not a 40 hour per week job.
Graduate students can expect to work an average of 50 hours per week.
Outside of the workday, you are welcome to work from the lab, or—as long as you ensure confidentiality of data—from home or from other spaces.
That said, the most important thing is for you to get the job done—you are in your career now and are investing in yourself.
Graduate research requires full-time dedication and year-round effort.

Discuss policies on work hours, sick leave, and vacation with me directly.
It is important to take time off to decompress from time to time.
Work-life balance and vacation time are essential for creative thinking and good health, and I encourage you to take regular vacations.
Each lab member can usually take up to [3 weeks of vacation time](https://grad.uiowa.edu/graduate-student-employment-agreement/paid-leaves-and-holiday) each year.
In addition, I do not expect students to work between 12/15 and the first week of January.
Per [Grad College policies](https://grad.uiowa.edu/graduate-student-employment-agreement/paid-leaves-and-holiday), please discuss your vacation plans with me before booking your trip.
Consult with me and notify fellow lab members in advance of any planned absences, with as much advance notice as possible—at least two weeks' notice or more if feasible.
Please plan that if you are away, others will need to take over your responsibilities, so planning for adequate lead time and training may be necessary.
Please discuss with me if you plan to take a summer internship or bootcamp.

## Meetings

There are three types of meetings: lab meetings, group meetings, and one-on-one meetings.
Lab meetings occur weekly.
All lab members are expected to attend.
Typical forms of lab meetings are article discussions (led by one lab member), project presentations, talks given by guest speakers, and professional development workshops.
You should read these materials in advance.
You are expected to contribute with questions and/or comments during lab meetings.
The university and our lab use Outlook for scheduling; you are expected to keep your university Outlook account up to date.

One-on-one meetings are 45-min, weekly meetings between each trainee and me.
You can also schedule one-off one-on-one meetings with me.
When scheduling your one-on-one and other meetings, send all of your available times (between 9am and 5pm), not just your preferred times! You may indicate which of your available times are preferred or less preferred.
One-on-one meetings are designed for us to discuss any training and research-related issues in detail and to form plans for the near future, in addition to any challenges.
Make sure that you also use this time to communicate new ideas that you have about your work and challenges that you are facing.
Remember: I cannot address or advise about issues that you do not bring to my attention.
I expect trainees to attend all their one-on-one meetings.
I understand that sometimes there is nothing to report, so occasional cancellation is fine.
That said, note that even if you have nothing to report, sometimes having the meeting can still be advantageous and it may be worth our time to still check in.
Do not cancel meetings with me if you feel that you have not made adequate progress on your research; these might be the most critical times to meet with a mentor.

You are expected to ask questions and take notes during meetings.
Be respectful of my time and make any necessary changes (to papers, analysis code, etc.) after the meeting, based on your notes and on your own time—unless I am working on the document directly.

Besides meetings, trainees are welcome to drop by my office anytime to discuss research, training, and administration-related issues.
I have an open-door policy: my door is always open (figuratively speaking).
I will be happy to meet with you as long as I do not have another obligation.
My office and phone number is: [see [my University page](https://psychology.uiowa.edu/people/isaac-petersen)].
My cell is: [blinded for the internet…just ask].

## Open science

We, as a lab, value and strive to advance the mission of [open science](https://onlinelibrary.wiley.com/doi/10.1002/icd.2315) to improve the accessibility, reproducibility, and replicability of science.
As such, all lab members are expected to conduct research transparently and to promote reproducibility.
This includes, but is not limited to, pre- or co-registering studies, sharing analysis scripts and data, using version control (GitLab), submitting [preprints](https://psyarxiv.com) when submitting a manuscript to a journal, and providing support for other labs' attempts to replicate and reproduce our findings.
We use GitLab for version control.
Our lab's template for GitLab repositories can be found here: https://research-git.uiowa.edu/PetersenLab/Template.
Our lab's template for projects on the Open Science Framework (OSF) can be found here[^2]: https://osf.io/4w9sv.

## Collaborations

All lab members are encouraged to explore collaboration opportunities both within and outside of the lab.
I ask trainees to (1) respect your collaborators' time and resources, and (2) inform me if you are seeking collaborations with or are collaborating with researchers (e.g., finishing your projects in your previous lab) outside of the lab.
Trainees are expected to have a firm footing in their research progress in this lab before collaborating with outside researchers.
I expect you to discuss order of authorship with me early on when there are potential collaborators.

## Readings and resources

Trainees are expected to read foundational articles relating to the lab and to their research interests.
Examples of foundational articles are on the lab's Google Drive folder of primer articles[^2].
I also expect you to read one of the primer articles by Schwartz (2008) titled, "The Importance of Stupidity in Scientific Research." It is important to feel comfortable feeling stupid in science; if you (and any of us) don't feel stupid, we're not doing science right! It is also important to read background information and protocols about our projects.

We have a list of lab resources for graduate students on our Lab's Trello board called "Grad Students"[^2]: https://trello.com/b/WjqbgpW9/grad-students.
The Trello board includes items for onboarding, important foundational skills for scientific training, useful software, and relevant journals, organizations, conferences, and listservs.
It also includes training materials for various software (e.g., REDCap, GitLab, R).
And it includes a list of the times to block off during the semester.

## Training

I expect you to take ownership over your educational experiences.
Your education is your responsibility—you have the primary responsibility for the successful completion of your degree.
I encourage you to follow the [recommended timelines](#timelines) for [research](#timeline-research), [coursework](#timeline-coursework), and [clinical work](#timeline-clinical) (see the Appendix). 
You should maintain a high level of professionalism, self-motivation, engagement, scientific curiosity, and ethical standards.
You should also be knowledgeable of and comply with all policies, deadlines, and requirements of the graduate program, the graduate college, and the university.
Further, I expect you to actively cultivate your professional development.
UI has outstanding resources in place to support professional development for students, including professional development seminars and workshops on topics such as oral communication, scientific writing, collaborative research, statistical methods, teaching, and mentoring.
I expect you to take advantage of these resources.
You are also encouraged to talk with other members of the lab, other students, and faculty to learn ways of effectively navigating graduate school.

Avoid clinical clique-ishness and insularity.
The most innovative science transcends traditional boundaries.
I expect you to spend time and talk science with graduate students and faculty in areas outside of clinical (e.g., BCN, cognition)—both to broaden your perspectives and to incorporate basic science perspectives into your work, while also being a good Departmental citizen.
Clinical students at some programs wrongly think they are special and think of their work as superior to basic science.
Clinical science is not a research area—clinical science uses basic science (e.g., cognitive, social, developmental, biological science) in rigorous ways to answer clinically relevant questions.

I expect all trainees to comply with their respective training plans (e.g., training plans of your degree program), such as taking required courses, maintaining passing grades, fulfilling teaching assistant duties, clinical training, and organizing committee meetings.
You are expected to attend and actively participate in all group meetings and in seminars that are part of your educational program.
I expect you to attend conferences, Clinical Rounds, Developmental Discussion, Data Team and lab meetings, DeLTA Center, Friday colloquia series, and other relevant brownbags such as Cognition, Behavioral & Cognitive Neuroscience (BCN), and the Iowa Neuroscience Institute (INI).
When we go to conferences, I will introduce you to my professional network and encourage you to build skills in networking.
We will discuss your training and career development plans.
All program requirements are in the Department's [Graduate Handbook](https://psychology.uiowa.edu/grad-program/graduate-handbook) and/or the Graduate College's [Manual of Rules and Regulations](https://grad.uiowa.edu/academics/manual).
I include a suggested timeline for your research, clinical training, and coursework in the following pages.

For some students, there may be relevant training fellowships.
For instance, the Behavioral-Biomedical Interface Training Program (BBIP) provides training in bio-medical research.

This is a research-oriented program; you are expected to prioritize research relative to your other obligations.
If you are getting all As in classes, you are spending too much time on coursework! [Grades in grad school don't matter](https://phdcomics.com/comics/archive.php?comicid=469) (as long as you pass your classes), and the sooner you figure that out, the better off and more productive you will be.
Instead of focusing your learning on coursework, learn by doing.
Take what you need from classes to advance your research program.

Please refer to the Clinic Manual for guidelines regarding face-to-face hours (on the clinic drive[^3]: `\\iowa.uiowa.edu\shared\CLAS\Departmental\PBS\Clinic\Clinic Manual`).
For clinical students, it is important to regularly track your clinical experiences and hours to ensure that you are meeting appropriate milestones in your training.
I highly recommend using Time2Track or PsyKey to track clinical hours.
We will discuss your plans for clinical training and practicum opportunities during our regular individual meetings.
I will also provide clinical supervision of some of your cases as part of the Seashore Clinic.
I am a licensed clinical psychologist, so assessment hours in my research lab count as clinical hours.

## Software

My lab primarily uses R for data management and analysis because it is free, open source, open platform, code-based (which increases share-ability and reproducibility of analyses), and supports advanced statistics and state-of-the-art graphics from packages designed by statistical experts all over the world, and to which anyone (including you) can contribute.
We also use MATLAB for processing of event-related potential data and Mplus for structural equation modeling.
You are encouraged to learn R and any other specialized software that will allow you to answer the research questions you are pursuing.
If there's another tool or software package that can do something easier, better, more efficiently, or with greater reproducibility than what we are using, feel free to use it—though I may not be able to provide formal guidance.
For instance, Python is a free programming language that is emerging as a nice complement to R for statistical programming.
No matter which software you use, you should be able to understand and explain what the analysis is doing and be able to interpret and explain the output.

## Best practices

I expect you to follow open science practices (described above).
I expect you to comment your code so that others can understand it (and so you can understand it when you go back to it 5+ years later).
I expect you to use version control (git with GitLab) with all projects and to save your lab projects in a repo on the [lab's GitLab page](https://research-git.uiowa.edu/PetersenLab).
Commit and push your work to the GitLab repo often.
Using version control provides many benefits: (a) it provides backups of all files in the cloud, (b) it allows you to access the files in the cloud from any computer with access to the internet, even if you are away from your local computer, (c) it provides history of all (committed) changes made to all files.
If you make a mistake in your code, you can easily revert to a prior version because you took snapshots (commits) of your files! (d) It allows you to write cleaner code because you do not need to keep all the old, "commented out" lines of code, (e) it helps with project organization; you no longer have to keep files or folders named "project_old" (or "project_2", "[project_final](https://phdcomics.com/comics/archive.php?comicid=1531)", or whatever), (f) it keeps all files for the project self-contained, which helps increase reproducibility, and (g) it allows easier collaboration with others on the project.

## Other responsibilities

I expect you to be a team player, to contribute to the team, and to take a leadership role in the lab.
Strive to be the very best lab citizen and citizen of the Department and University.
Regardless of your source of funding (e.g., teaching assistantship, research assistantship, fellowship/grant), you can expect lab-related assignments that are for the betterment of the team.
For instance, I expect you to supervise a coding task.
I expect you to learn the lab procedures and protocols.
You should be able to train research assistants or lab staff on various procedures.
I expect you to work to ensure quality control of lab procedures so that we are collecting and processing high-quality data in an efficient way.
I expect you to help other team members, including undergraduate research assistants with independent research projects, Honors projects and theses, job or graduate applications/interviews, etc.
Doing so will help you build important skills in mentoring.

Regardless of your source of funding, you are expected to spend most of your time doing lab-related research.
If you are funded on a research assistantship from the lab, I expect you will spend at least 20 hours (for a full-time assistantship; at least 10 hours for a half-time assistantship) doing lab-related research from the relevant grant(s) and lab-assigned work that is separate from coursework, clinical work, work toward program requirements (e.g., Comps exams), other research-related work, and other endeavors.
This is an ethical obligation given our federal sources of funding.
If you are unable to commit to a full research load (and therefore would not be able to meet the expectations of a research assistantship), you should tell me before assistantships are assigned, so you can be given a teaching assistantship or another source of funding.
Nevertheless, even with a teaching assistantship, you are expected to spend most of your time doing lab-related research.
You should not spend more than 10 hours per week doing teaching-related work for a half-time teaching assistantship, and not more than 20 hours for a full-time teaching assistantship (and generally much less than that).

You should talk with me and get my approval before doing or adding any external practica.
You should not spend more than 1.5 full days (i.e., 12 hours) doing clinic-related work per week.
Don't focus too much on clinical hours; Ph.D.
students from non-clinical science programs and Psy.D.
students will have way more clinical hours than you—you are not competing with them for the same types of sites.
You will be most competitive at [clinical science internship sites](https://www.acadpsychclinicalscience.org/internship-programs.html), which care much more about the *quality* of training than the *quantity* of training.
And UI has top-notch clinical training.
Internship sites also care heavily about scientific productivity including publications ([Lund et al., 2016](https://psycnet.apa.org/record/2015-57073-001)), and this is even more true for clinical science internship sites.
I had four first-authored publications (nine total) and an NRSA when I applied for internship and received 13 interview invitations out of 15 sites.
I am happy to share my preparation, application, and interview materials etc.
for internships, jobs, etc.
and to work with you to make them as strong as possible.

Please don't hide in your office; get out and meet people at group and departmental events.
If a colloquium is given in an area in which you have a research interest, sign up to meet with the speaker.
Go up to speakers after talks, introduce yourself, and express interest in their work by asking questions.
Networking skills are important and can often lead to job opportunities.

## Career development

I strongly believe that the lab grows better with each trainee achieving their career goals.
I respect and support each trainee's career choice and understand that things can change over time.
At the same time, keep in mind that this is a [research-oriented training program](https://psychology.uiowa.edu/graduate-program) and is best aligned with careers in which research will be a key component.
For prospective graduate students, if you have goals of being a clinician, I would dissuade you from joining our program and this lab; you would not be happy here.

We will discuss your career development plans and how I can best support them.
During your first semester, I expect you to complete an Individual Development Plan ([https://myidp.sciencecareers.org](https://myidp.sciencecareers.org)), and to review and discuss the results with me.
I also expect you to inform me if there is any change in your plans so that your lab activities can be better aligned to your new goals.
In addition to academic careers (e.g., research/teaching/clinical work at R1 university, academic medical center, or liberal arts college), I support plans for industry and non-academic careers (e.g., data science, consulting, government, NGO; these are just examples—there are many others).
You are welcome to get the training you need, provided that you maintain good progress on your degree-related training and research.
Seek the experience of faculty, professionals, post-docs, and other students to help you out.

If you want an academic job, I know what it takes to get one (in terms of publications, grants, etc.), so just ask.
I'm also happy to talk with you about what an R1 academic job is like (e.g., setting up and running a lab, teaching)—I love my job and have a passion for the work we do.
I get to be part of an invigorating intellectual environment in which I get to learn every day, get to be around exciting ideas and world-renowned experts conducting cutting-edge research, and have the intellectual freedom to get paid to study whatever I want to study.
I can't imagine anything better.
That said, there aren't enough faculty positions for all Ph.D.
graduates and it's not the best fit for everyone.
I will work with you to find the career that is the right fit for you.

## My approach to mentorship

As a clinical-developmental psychologist, I take a developmental perspective to mentorship.
Early on in your training, I aim to provide sufficient structure and scaffolding.
As you develop proficiency in a skill, I strive to withdraw the scaffolds so that you develop independence and autonomy.
The second approach to my mentorship style is an emphasis on learning by doing.
I encourage students to learn by applying the skills to projects they are working on in the lab, rather than relying on coursework and other methods.
I view my role as fostering your professional confidence and encouraging your critical thinking, skepticism, and creativity.

Do not hesitate to ask questions if I am around; it is often better to ask questions than to make a mistake that could have been easily avoided.
I am periodically away, and I expect you to get things done well without me.
You are encouraged to be independent; don't be afraid to try to do detective work on your own if I am not around.
There is also a benefit to learning by trial and error.
We have a helpful, experienced lab, so know that people other than me may be excellent resources.

In order for supervision to be effective, I hope that our relationship will include open communication and two-way feedback.
If there are ways I can be a better mentor for you, please let me know.
I value openness to learning as a continuous, developmental, life-long process and I will model and promote openness and receptivity to feedback.
I expect that trainees will express disagreements and differences in opinion with me.
I do not view professional disagreements as personal; the best science arises out of the free and constructive exchange of multiple perspectives and ideas.
I expect that trainees will attempt to address conflicts in the mentor–mentee relationship.

I strive to build and to support a diverse team, to treat people equitably, and to be inclusive of people from all backgrounds.
If there are things that the lab or I can do to help you or others feel more included, please let me know.

I am committed to mentoring you, even after you leave my lab.
I am committed to your education and training while you are in my lab, and to advising and guiding your career development—to the extent you wish—long after you leave.
I will provide honest letters of evaluation for you when you request them.

## Communication

Feel free to use Slack for brief communication with me.
However, we do not use direct messages in Slack (see the lab manual).
All Slack communication should be in team-facing channels so others can benefit from the information and so we can go back and reference it later.
For longer communication, please call or stop by my office.
I find this much more efficient and pleasant than writing and reading lengthy communication.
For sending manuscripts, personal information, and messages that do not need an urgent response, you may email me.
Please limit your use of email as much as possible.
[I hate email](https://www.chronicle.com/article/is-email-making-professors-stupid); we get way too much of it, it is impersonal, it doesn't communicate tone well (often leading to misinterpretation and sometimes hurt feelings), and it is difficult for me to stay on top of my inbox.
I encourage you to stop by my office or to call my office phone instead of relying on email, whenever possible.

When you contact me or send me materials, you can expect me to respond promptly.
Likewise, I expect you to respond promptly when I or another lab member contacts you (in most cases, within 48 hours).
If you need time to gather information in response to a Slack message or email, please acknowledge receipt of the message and indicate when you will be able to provide the requested information.
At times, I may contact you by email or Slack after hours (if that is when it is most convenient, so that I do not forget to).
However, you are \*not\* expected to respond after hours.
I will call you if something is urgent.

Be mindful of the constraints on my time.
Allow a minimum of one week prior to submission deadlines for me to read and respond to short materials such as conference abstracts and three weeks for me to work on manuscripts, grant proposals, and letters of recommendation.
Please do not assume I can read materials within a day or two, especially when I am traveling.
Please only send drafts of manuscripts, grant proposals, dissertations, etc.
when they are your <ins>best possible work</ins> (the Henry Kissinger criterion).
That means going through multiple revisions, reading it out loud to yourself, etc.
Here's an excerpt about Dr. Kissinger ([Krausman, 2021](https://wildlife.onlinelibrary.wiley.com/doi/10.1002/jwmg.21992)):

> "Henry Kissinger, a former Secretary of State under President Nixon, understood the importance of continually improving writing skills.
> Winston Lord was Kissinger's speech writer and during the late 1960s and early 1970s, Lord had been tasked with writing a speech about three important foreign policy projects: the opening of China to the West, bringing the Vietnam War to a close, and an attempt to improve relations with the Russians.
Writing a speech for Kissinger was not an easy job because Kissinger was a speech writer himself and harsh critic.
> 
> The story goes that Lord prepared and submitted a first draft of a speech to Kissinger one evening.
> Kissinger then called Lord the next morning for feedback on the speech and asks "Is this the best you can do?"
> 
> Lord replies "Henry, I thought so, but I'll try again."
> 
> Lord then went back to the drawing board, tweaked, revised, and resubmitted another draft a few days later.
> 
> The next day, Kissinger called Lord into his office and again asked "Are you sure this is the best you can do?"
> 
> Lord began to question his work and said "Well, I really thought so. I'll try again."
> 
> Believe it or not, this uncomfortable and rejecting process went on for 8 drafts, each time Kissinger standing firm to his original feedback of "Is this the best you can do?"
> 
> Lord returned to Kissinger's office with the now ninth draft and awaited his response.
> 
> Surely enough, Kissinger called Lord in the next day and asks him the same question, "Is this the best you can do?"
> 
> Lord, now completely fed up, furiously replied "Henry! I've beaten my brains out—this is the ninth draft! I know it's the best I can do; I can't possibly improve one more word!!!"
> 
> Kissinger then looked at Lord and nonchalantly said "Well, in that case, now I'll read it."

## Lab culture

Within a lab environment, occasionally competitive thoughts or emotions may arise.
This lab is not a place for competition, but collaboration.
We are a group of researchers working toward a common goal, and all members are encouraged to work together collaboratively.
A rising tide lifts all boats.
Competitive behavior is not conducive to a productive laboratory, and this sort of behavior will strictly not be tolerated.
Don't compare yourself to others.
You are on your own path.
Each mentee needs different things, and I will do my best to get to know you as an individual, and your individual skills, preferences, and goals.
Cultivating a common value of humility is important in research, because we are always asking questions to which we inherently do not know the answer.
Elitist behavior is not conducive to growth and development, and as such, is not appropriate for the lab environment.
The lab culture is of utmost importance to a healthy, functional group, and professional behavior is at the center of building this culture.
If you have joined the lab, you have been selected among many qualified applicants for this position.
I encourage you to share your thoughts and ideas with the lab.
Keeping them to yourself would be a disservice to the team.

## Professionalism

Show up on time, fully prepared for meetings.
If you will need to miss a meeting, let the relevant team members know in advance, with as much advance notice as possible.
Unexcused absences are not acceptable in a professional environment.

If you have critical thoughts to share with someone, do not send them in Slack or in email; instead, call or talk to the person directly.
Be responsive to advice and constructive criticism.
The feedback you get from me, your colleagues, your committee members, your course instructors, your clinical supervisors, and your teaching supervisors is intended to improve your work and help you succeed.
Do your best not to take it personally.
We all have room to grow.

## Interactions with others

We succeed (and fail) as a team.
I expect all lab members to respect each other.
This includes treating others with kindness and compassion, addressing others respectfully (e.g., using appropriate titles, pronouns), listening when others speak, and allowing others to share their perspectives.
This lab has a zero-tolerance policy for harassment or discrimination of any kind.
Statements and behaviors that are demeaning or aggressive will not be tolerated.
Likewise, lab members are also expected to respect colleagues in the Department and the University, and our participants.

If another member of the lab is not complying with these policies, please first attempt to speak to the person directly.
The APA Code of Ethics advises that this is a first step toward resolution.
If that is not possible, appropriate, or proves ineffective (i.e., does not change behavior), please speak to me about the problem immediately.
Please also speak to me if you think you have an interpersonal issue with me.
If, after having talked with me, you feel the issue will not be resolved and you want to speak to someone else to address the issue, follow the chain of command and talk to the Area Coordinator, the Director of Graduate Studies, and/or the Departmental Executive Officer.
The chain of command is depicted in the [lab organizational chart](https://devpsylab.github.io/LabWiki/manual.html#organizationalChart).

## Consequences of non-compliance

If I become aware of violations of our values or policies, I will discuss the matter with the person directly and in close temporal proximity to being made aware of the situation.
I will first attempt to understand the situation, including both the behaviors and the antecedents.
I will also try to clarify expectations and provide constructive feedback around the specific task, behavior, interpersonal interaction, or scenario.
Discussion will center on prevention of such behaviors in the future.
The consequences will vary based on the specific behavior, and may include consequences such as: meeting individually with me and possibly other departmental leadership, making repairs with the other party, development of a plan to monitor and correct the behavior so it does not recur, dismissal from the lab, and dismissal from the program.

## Performance improvement plan

In the case that your progress is unsatisfactory for an extended period, we need to discuss and implement a plan to improve your performance, which eventually will be helpful for your career plan, too.
The performance improvement plan will likely involve closer monitoring of your progress and research activities until a predefined goal is reached (e.g., publishing a paper).

## Accommodations

Sometimes, life events or medical/health-related issues may impact your ability to meet some of the lab expectations.
You are encouraged to seek medical/professional help if such issues arise, even if the appointments occur during your regular lab hours.
If there are lab-related accommodations that would be helpful to you, please let me know and/or contact the UI Student Disability Services (https://sds.studentlife.uiowa.edu).
Any deviations from the lab expectations should be approved by me or should coincide with documentation from UI Human Resources or Student Disability Services outlining alterations.
If you have concerns about meeting your responsibilities or expectations, please talk to me.

## Well-being

Last but not least, your well-being is very important.
I went through the process of graduate school and understand how stressful things can be from my own experiences.
If you feel down for any reason, please talk to me or anyone you feel comfortable talking to.
You are also encouraged to seek professional help—it is not a sign of weakness; it is a sign of you taking care of yourself.

Remember that all of us are "new" at various points in our careers.
Imposter syndrome is normal; I encourage you to adopt a growth mindset.
You are meant to be here! Failure is common in academia.
Take a look at the [CV of Failures](https://www.uni-goettingen.de/de/document/download/bed2706fd34e29822004dbe29cd00bb5.pdf/Johannes_Haushofer_CV_of_Failures%5b1%5d.pdf).
Persistence pays off.
I have found it helpful to have a ["feelgood" email folder](https://blogs.scientificamerican.com/guest-blog/the-awesomest-7-year-postdoc-or-how-i-learned-to-stop-worrying-and-love-the-tenure-track-faculty-life/) that I can refer back to when things are difficult.

Don't forget to laugh and have fun! Graduate school is a challenging job with very high expectations, but it should also be fun.
You get to study something that is exciting to you and get paid to do it! To quote [Norman Ramsey's guide for graduate students](https://d1uqjtzsuwlnsf.cloudfront.net/wp-content/uploads/sites/163/2016/11/Ramsey-Guide-for-Research-Students.pdf), "To sustain yourself through difficult times, find research that means a lot to you.
Successful researchers find interesting problems and fall in love with them.
In operational terms, some Friday nights should be spent having fun out in the world, but if you aren't also spending some Friday nights having fun with your research, you're not doing the right research."

# Signature

I have read and understand the above expectations, in addition to the [lab manual](https://devpsylab.github.io/LabWiki/manual.html) and the section on [expectations for everyone in the lab](https://devpsylab.github.io/LabWiki/expectations-everyone.html).
I agree to meet these expectations and to ask Dr. Petersen if I need clarification on any of the expectations and systems of lab.

Mentee's Signature _________________________________	Date ____________



Mentor's Signature _________________________________	Date ____________

# Appendix

## Approximate Expected Timelines {#timelines}

### Research Timeline {#timeline-research}

| **Semester**   | **Research Task Goal(s)**                                                    |
|----------------|------------------------------------------------------------------------------|
| Year 1: Fall   | Form Research Advisory Committee (RAC)                                       |
|                | Select topic for 1st year project                                            |
|                | Background readings on topic and quantitative methods                        |
|                | Begin writing literature review for 1st year project                         |
|                | RAC Meeting                                                                  |
| Year 1: Spring | Complete literature review for 1st year project                              |
|                | Begin methods and data analysis for 1st year project                         |
|                | RAC Meeting                                                                  |
| Year 2: Summer | Complete analysis for 1st year project                                       |
|                | Write-up results and discussion section for 1st year project                 |
| Year 2: Fall   | 1st year project written document due (Monday after Thanksgiving)            |
|                | RAC Meeting                                                                  |
| Year 2: Spring | 1st year project presentation to department                                  |
|                | Submit 1st year project for publication                                      |
|                | Begin formulating comprehensive paper topic                                  |
|                | RAC Meeting                                                                  |
|                | Form Comprehensive Exam Committee                                            |
| Year 3: Summer | Flesh out comprehensive paper topic                                          |
|                | Write comprehensive paper proposal                                           |
| Year 3: Fall   | Comprehensive Paper Proposal Meeting                                         |
|                | Write comprehensive paper                                                    |
| Year 3: Spring | Turn in Comprehensive Paper Draft 1 (second Monday in February)              |
|                | Receive feedback from committee (3 week turn-around)                         |
|                | Revise and resubmit comprehensive paper (Monday before last week of classes) |
|                | Final Comprehensive Exam Committee meeting with oral defense                 |
| Year 4: Summer | Begin work on dissertation prospectus                                        |
| Year 4: Fall   | Form Dissertation committee                                                  |
|                | Continue writing dissertation prospectus                                     |
| Year 4: Spring | Complete dissertation prospectus                                             |
|                | Defend Dissertation Prospectus (by spring break)                             |
|                | Begin dissertation research                                                  |
| Year 5: Summer | Dissertation research                                                        |
| Year 5: Fall   | Dissertation research                                                        |
|                | Apply for internship                                                         |
| Year 5: Spring | Dissertation research                                                        |
|                | Interview for internship                                                     |
|                | Defend dissertation                                                          |
| Year 6: Summer | Begin Internship                                                             |
| Year 6: Fall   | Internship                                                                   |
| Year 6: Spring | Internship                                                                   |
| Year 7: Summer | Graduate with Ph.D.!                                                         |

These are guideposts toward completing program requirements within a 5-year timeframe.
As we have discussed, my expectation is that you will be engaged in research activities *beyond* those required by the program.

### Coursework Timeline {#timeline-coursework}

| **Semester**   | **Coursework Goal(s)**                                                             |
|----------------|------------------------------------------------------------------------------------|
| Year 1: Fall   | Orientation to Clinical Research (with DCT)                                        |
|                | Quantitative Methods Course                                                        |
|                | Descriptive Psychopathology OR Psychological Therapies                             |
|                | Introductory Practicum                                                             |
|                | Research                                                                           |
| Year 1: Spring | Quantitative Course                                                                |
|                | Principles of Psychological Assessment                                             |
|                | Ethics OR Breadth Course (History, Cognitive, Social, Biological, Developmental)   |
|                | Assessment Practicum                                                               |
|                | Research                                                                           |
| Year 2: Summer | Assessment Practicum/Ethics 3-week course possibility                              |
| Year 2: Fall   | Descriptive Psychopathology OR Psychological Therapies                             |
|                | Ethics OR Breadth Course                                                           |
|                | Assessment Practicum                                                               |
|                | Research                                                                           |
| Year 2: Spring | Ethics OR Breadth/BBIP Course                                                      |
|                | Breadth Course                                                                     |
|                | Therapy practicum                                                                  |
|                | Research                                                                           |
| Year 3: Summer | Therapy Practicum                                                                  |
| Year 3: Fall   | Breadth Course                                                                     |
|                | Research                                                                           |
|                | Therapy practicum                                                                  |
| Year 3: Spring | Breadth Course                                                                     |
|                | Research                                                                           |
|                | Therapy practicum                                                                  |
| Year 4: Summer | Therapy Practicum                                                                  |
| Year 4: Fall   | Breadth Course (if needed)                                                         |
|                | Research                                                                           |
|                | Therapy practicum                                                                  |
| Year 4: Spring | Breadth Course (if needed)                                                         |
|                | Research                                                                           |
|                | Therapy practicum                                                                  |
| Year 5: Summer | Therapy Practicum                                                                  |
| Year 5: Fall   | Dissertation Research                                                              |
|                | Therapy/External Practicum                                                         |
| Year 5: Spring | Dissertation Research                                                              |
|                | Therapy/External Practicum                                                         |
| Year 6         | Internship                                                                         |

**Clinical Science Area Course Requirements**

- 3 Clinical Core Courses (Psychopathology, Therapies, Assessment)
- 2 Quantitative Courses
- 4 Breadth Courses (Biological, Cognitive, Developmental, and Social Bases of Behavior)
- History & Systems
- Ethics
- \*Behavioral-Biomedical Interface Training Program (BBIP) required course (if you are part of BBIP)

Note: Breadth courses can be completed with directed readings.

### Clinical Work Timeline {#timeline-clinical}

| **Semester**   | **Clinical Task Goal(s)**                                                                       |
|----------------|-------------------------------------------------------------------------------------------------|
| Year 1: Fall   | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
|                | Work with advanced graduate students on assessment skills                                       |
|                | Interviewing practicum with Clinic Director                                                     |
| Year 1: Spring | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
|                | Work with advanced graduate students on assessment                                              |
|                | Begin completing ID assessments in clinic                                                       |
|                | Interviewing practicum with Clinic Director                                                     |
| Year 2: Summer | Continue ID assessments, begin SDS assessments                                                  |
| Year 2: Fall   | Complete SDS and DHS assessments in Seashore Clinic                                             |
|                | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
|                | Weekly 2nd year seminar with Clinic Director (Motivational Interviewing, Behavioral Activation) |
| Year 2: Spring | Complete assessments in Seashore Clinic                                                         |
|                | Begin taking therapy cases in Seashore Clinic                                                   |
|                | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
|                | Weekly 2nd year seminar with Clinic Director (Motivational Interviewing, Behavioral Activation) |
| Year 3: Summer | Complete assessments in Seashore Clinic                                                         |
|                | Work with therapy cases in Seashore Clinic                                                      |
| Year 3: Fall   | Complete assessments in Seashore Clinic                                                         |
|                | Work with therapy cases in Seashore Clinic                                                      |
|                | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
|                | Weekly 3rd year seminar (Exposure Therapy and other approaches)                                 |
| Year 3: Spring | Complete assessments in Seashore Clinic                                                         |
|                | Work with therapy cases in Seashore Clinic                                                      |
|                | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
|                | Weekly 3rd year seminar (Exposure Therapy and other approaches)                                 |
| Year 4: Summer | Complete assessments in Seashore Clinic                                                         |
|                | Work with therapy cases in Seashore Clinic                                                      |
| Year 4: Fall   | Seashore Clinic work and/or External Practicum                                                  |
|                | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
| Year 4: Spring | Seashore Clinic work and/or External Practicum                                                  |
|                | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
| Year 5: Summer | Seashore Clinic work and/or External Practicum                                                  |
| Year 5: Fall   | Seashore Clinic work and/or External Practicum                                                  |
|                | Attend Clinical Rounds (Mondays from 12:30-1:20)                                                |
|                | Apply for internship                                                                            |
| Year 5: Spring | Interview for Internship                                                                        |
| Year 6         | APA-Accredited Internship                                                                       |

[^1]: Many of the lab expectations were cobbled together from a variety of other labs and are not unique to this lab.
  Likewise, some of the language used in this document was borrowed from other sources.
  
[^2]: Ask me to give you access.
  It is easiest to share the Google Drive folder of primer articles with your Google account.

[^3]: You need to be on the VPN to access.
  You may need to contact the clinic director to get access to the Clinic Drive.
