---
title: "Lab Expectations for SROP Students"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  comment = "")
```

# What Does SROP Entail? {#srop}

The University of Iowa's Summer Research Opportunities Program (SROP) is an eight-week program designed to provide undergraduate students from underrepresented backgrounds with in-depth research experiences.
As part of the SROP program, you will conduct an independent research project and will present your findings at a University of Iowa undergraduate research conference.
To help you accomplish this, our goal is to get you set up as quickly as possible with our data so that you can formulate a research question and hypothesis, identify and extract the relevant data available, learn and perform the data analysis to test your question, and put together an abstract and poster for the SROP presentation—all on the eight-week timeline.

For more informaton on the UI SROP Program, see here: https://grad.uiowa.edu/dei/srop

# Lab Expectations {#expectations}

The following are lab expectations for SROP students:

- You and Dr. Petersen will have a weekly one-on-one meeting to ensure you are making progress on your independent research project
- You will attend weekly lab meeting
- Whenever you are not in a SROP program meeting, you will be working in the lab (during regular business hours; 9am–5pm Monday through Friday)
- You will let us know, in advance, if you will be late to your scheduled shift or will not be able to make your scheduled shift

# Resources {#resources}

The focal project of the lab's work is an ongoing longitudinal study, the [School Readiness Study](study-schoolReadinessStudy.html), that follows children from 3–7 years of age to better understand how self-regulation and externalizing problems develop, from a bio-psycho-social perspective.
For more information on the study, you are encouraged to read papers from the project, view the available measures, examine the Data Dictionary, and see the pre-registered hypotheses.
These resources are available on the project page for the [School Readiness Study](study-schoolReadinessStudy.html).
For information on how to conduct data analysis, see the relevant sections of the lab's Data Analysis guides on [`SPSS`](https://devpsylab.github.io/DataAnalysis/SPSS.html) or [`jamovi`](https://devpsylab.github.io/DataAnalysis/jamovi.html).

# Expectations for Everyone in Lab {#expectationsForEveryone}

In addition to the expectations described above for SROP students, please also read the [expectations for everyone in the lab](expectations-everyone.html).

# Signature {#signature}

Please download, sign, and email the below document to Dr. Petersen prior to your first day in lab.

<embed src="Files/signature_page.pdf" width="1000" height="600">
