---
title: "Lab Expectations for Everyone"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

Everyone is expected to follow our [mission statements](https://devpsylab.github.io/LabWiki/manual.html#missionStatement), including our [internal](https://devpsylab.github.io/LabWiki/manual.html#missionStatement-internal) and [external](https://devpsylab.github.io/LabWiki/manual.html#missionStatement-external) mission statement, in addition to our [diversity statement](https://devpsylab.github.io/LabWiki/manual.html#diversityStatement).

# Professionalism

Everyone is expected to act professionally.
This is especially critical when participants are in the lab.
When a participant is in the lab, they should not be able to hear anyone in either the observation room or the lab offices.
In longitudinal research, each visit is exponentially more important than the last.
Treating participants like royalty is not only the right thing to do, but significantly increases the likelihood of retention.

# Dress Code {#dressCode}

While in lab and on days when you do *not* have lab-related meetings outside of the Department:

Everyone is expected to follow a "casual professional" (i.e., "business casual") dress code while in lab.
Jeans and denim capris are acceptable when in lab, as long as they are not ripped or frayed.
T-shirts without inappropriate graphics, text, cut-outs, etc. are acceptable.
Leggings are permitted if they are worn as tights (i.e., under a skirt, dress, shorts, or long shirt that fully covers the bottom).
Shorts are permitted if they are twill or chino material and reach *at least* to your mid-thigh (Bermuda-length shorts, however, are more appropriate).
The following are NOT allowed: open-toed shoes, short-shorts, low-cut shirts, visible undergarments (including bralettes and sports bras), or workout/gym clothes (e.g., sweatpants, yoga pants).
For guidance on shorts guidelines, see the [DevPsy Lab Summerwear Guide](#summerwear) (below).

You are expected to dress more nicely on days that you have meetings outside of the department (such as with community partners).
On these days, you should wear a nice pair of pants/dress/skirt and shirt; you should not wear jeans or shorts.

## DevPsy Lab Summerwear Guide {#summerwear}

Shorts are allowed if they are twill or chino material and reach at least to your mid-thigh (Bermuda-length shorts, however, are more appropriate).
This also applies to dresses and skirts—they must reach at least your mid-thigh, and are not advised for LV1 Es on visit days.
Denim jeans and capris are always allowed, as long as they are not ripped or frayed.
T-shirts are allowed, as long as they: do not have any inappropriate graphics or text, revealing cutouts or designs, or are cropped in length.
Please note, though, that your outfit cannot reveal any undergarments (including lace bralettes or sports bras).

**PRO TIPS FOR SHORTS IN A PROFESSIONAL ENVIRONMENT**

GO FOR LENGTH\
Choose a hem that’s appropriate for your unspoken office dress code— mid-thigh to Bermuda length are your best bet.

THE PERFECT STYLE\
Opt for a flowy fit with a simple graphic print.
While we know cut-offs and tight spandex styles are fun, these should be saved for after-work wear.
A sophisticated fabric, such as chino shorts, will help keep your ensemble fresh and professional.

https://www.stitchfix.com/women/blog/ask-a-stylist/are-there-work-appropriate-shorts

To pull off shorts at the office without raising alarm or workplace scorn, we compiled an Atkin-approved guideline of dos (and one don't).

- Do find shorts of an appropriate length.
"I would recommend mid-thigh to the knee—anywhere in that range."
- Don't wear short shorts.
That means, no booty shorts or frayed denim cut-offs.
- Do look for shorts cut from an elevated cloth.
Try "a chino material or cotton.
I like tailored shorts that have structure, but are also lightweight."
- Do seek out special detailing.
Pleats down the front, a clean hem, or a high-waisted silhouette are great examples.

https://www.instyle.com/news/summer-wear-shorts-office

The cardinal rule: Stay away from cutoffs, which are almost universally considered too casual for any workplace, and opt instead for a tailored pair of Bermuda-length shorts, which offer conservative hemlines and an overall more polished look.

https://www.realsimple.com/beauty-fashion/clothing/are-shorts-work-appropriate
While temperatures are warm outside, you might be tempted to dress down at the office and reveal more skin than you should.
But Clinton Kelly, co-host of TLC's "What Not to Wear" reality series, says, "Resist the temptation."

"When it comes to your career, the image you're projecting at work makes a difference in how far you're going to get in the company," he says.
"Don't use excuses like, 'It's hot outside,' to not dress appropriately."

[XXX][**INSERT IMAGES**]

# Role-Specific Expectations

In addition, people are expected to follow their expectations for the role, including expectations for [undergraduate research assistants](https://devpsylab.github.io/LabWiki/expectations-undergradRA.html), [graduate students](https://devpsylab.github.io/LabWiki/expectations-gradStudent.html), [postdoctoral scholars](https://devpsylab.github.io/LabWiki/expectations-postdoc.html), the [Lab Coordinator](https://devpsylab.github.io/LabWiki/expectations-labCoordinator.html), and [lab staff](https://devpsylab.github.io/LabWiki/expectations-labStaff.html).

