---
title: "Lab Expectations for Lab Coordinator"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      comment = "")
```

# Duties {#duties}

Duties for the Lab Coordinator include the following:

- Participant recruitment
- Participant scheduling
- Longitudinal tracking and retention of participants
- Data collection
- Data management
- Behavioral coding from video
- Supervision of research assistants
- Making lab space warm, welcoming, and child and family friendly
- Quality control and ensuring high-quality and efficient procedures
- Attending and contributing at lab meeting
- Supervision of lab staff
- Leading lab meeting
- Lab report

# Your Schedule {#schedule}

Here are the expectations regarding your schedule:

- You are in the office for 40 hours per week that are regularly scheduled between 9am–5pm Monday through Friday.
- You may have to work outside those hours (early mornings/evenings/weekends) for the purpose of running participants.
- You get approval from me for any deviations from this schedule (working outside those hours, working more than 40 hours, etc.), and update your schedule accordingly in the online calendar.
- The position involves fully in-person work.
- You let me and the relevant team members know by Slack if you will not be able to make it in for your regularly scheduled hours.
- You let me and the relevant team members know in person or by Slack if you are leaving the office (running lab errands, etc.).
- You keep your schedule in the online calendar up-to-date with any changes.
- You respond to team members promptly by email, Slack, or in person (within one business day).

# Communication {#communication}

- You will use Slack (or in person/phone) for most communication (see lab communication guidelines [here](manual.html#labCommunication)), but you will use the lab email (i.e., devpsy-lab@uiowa.edu; not your personal email) for all lab-relevant email communication.
This makes it easier for us to keep a record of lab-related communication for Dr. Petersen and future lab staff.
For ***non-lab*** related email communication, you will use your personal university email (i.e., firstname-lastname@uiowa.edu).
If someone contacts your personal university email with lab-related communication, you should reply using the lab email.
- I expect you to respond promptly when I or another lab member contacts you (in most cases, within 48 hours).
If you need time to gather information in response to a Slack message or email, please acknowledge receipt of the message and indicate when you will be able to provide the requested information.
At times, I may contact you by email or Slack after hours (if that is when it is most convenient, so that I do not forget to).
However, you are \*not\* expected to respond after hours.
I will call you if something is urgent.

# Lab Report {#labReport}

- We will have a weekly scheduled one-on-one meeting (in addition to other times I meet with you in the lab).
- You will submit a report no later than the day before so I can review it before our meeting and come prepared.
- The report should include:
    1. What you have accomplished since last week
    1. What you plan to accomplish in the next week
    1. Items to discuss, including problems, recommended solutions, and questions

# Expectations for Everyone in Lab {#expectationsForEveryone}

In addition to the expectations described above for the Lab Coordinator, please also read the [expectations for everyone in the lab](expectations-everyone.html).

# Signature {#signature}

Please download, sign, and email the below document to Dr. Petersen prior to your first day in lab.

<embed src="Files/signature_page.pdf" width="1000" height="600">
