---
title: "Lab Expectations for Lab Coordinator"
---

# Duties {#sec-duties}

Duties for the Lab Coordinator include the following:

- Participant recruitment
- Participant scheduling
- Longitudinal tracking and retention of participants
- Data collection
- Data management
- Behavioral coding from video
- Supervision of research assistants
- Making lab space warm, welcoming, and child and family friendly
- Quality control and ensuring high-quality and efficient procedures
- Attending and contributing at lab meeting
- Supervision of lab staff
- Leading lab meeting
- Lab report

# Your Schedule {#sec-schedule}

Here are the expectations regarding your schedule:

- You are in the office for *at least* 40 hours per week, during regular business hours: 9:00 AM–5:00 PM, Monday through Friday.
- You may have to work outside regular business hours (early mornings, evenings, or weekends) to run participant visits.
These hours are **in addition to** the standard 40-hour workweek.
It is important to me to help protect your time, and I will work with you to try to minimize these instances (e.g., getting research assistants to run visits) to the extent possible, but some visits may require you to help run them because of staffing constraints.
- You get approval from me in person, by phone, or by email for any deviations from this schedule (working outside those hours, listing more than 40 hours in your log if you log hours, etc.), and update your schedule accordingly in the online calendar.
If we discuss the schedule changes in person or by phone, you email me after we discuss to confirm the changes.
- If your position requires you to log hours, you log hours worked using your Employee Self Service and submit them to Dr. Petersen—your log should not exceed 40 hours in a week.
- The position involves fully in-person work.
- You let me and the relevant team members know by Discord if you will not be able to make it in for your regularly scheduled hours.
- You let me and the relevant team members know in person or by Discord if you are leaving the office (running lab errands, etc.).
- You keep your schedule in the online calendar up-to-date with any changes.
- You submit time off (or other) requests to me in person, by phone, or via email (not by Discord) with as much advance notice as possible—and at least 24 hours in advance, if at all possible.

# Communication {#sec-communication}

- You will use Discord (or in person/phone) for most communication (see lab communication guidelines [here](lab-manual.qmd#sec-labCommunication)), but you will use the lab email (i.e., [devpsy-lab@uiowa.edu](mailto:devpsy-lab@uiowa.edu); not your personal email) for all lab-relevant email communication.
This makes it easier for us to keep a record of lab-related communication for Dr. Petersen and future lab staff.
For personal communication (e.g., asking for time off) or ***non-lab*** related email communication, you will use your personal university email (i.e., firstname-lastname@uiowa.edu).
If someone contacts your personal university email with lab-related communication, you should reply using the lab email.
- You respond to team members promptly by email, Discord, or in person (within one business day).
- 
If you need time to gather information in response to a Discord message or email, please acknowledge receipt of the message and indicate when you will be able to provide the requested information.
At times, I may contact you by email or Discord after hours (if that is when it is most convenient, so that I do not forget to).
However, you are \*not\* expected to respond after hours.
I will call you if something is urgent.

# Lab Report {#sec-labReport}

- We will have a weekly scheduled one-on-one meeting (in addition to other times I meet with you in the lab).
- You will submit a report no later than the day before so I can review it before our meeting and come prepared.
- The report should include:
    1. What you have accomplished since last week
    1. What you plan to accomplish in the next week
    1. Items to discuss, including problems, recommended solutions, and questions

# Expectations for Everyone in Lab {#sec-expectationsForEveryone}

In addition to the expectations described above for the Lab Coordinator, please also read the [expectations for everyone in the lab](expectations-everyone.qmd).

# Signature {#sec-signature}

Please download, sign, and email the below document to Dr. Petersen prior to your first day in lab.

<embed src="Files/signature_page.pdf" width="1000" height="600">
