---
title: "Lab Expectations for Lab Staff"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      comment = "")
```

# Duties {#duties}

Duties for lab staff include the following:

- Participant recruitment
- Participant scheduling
- Longitudinal tracking and retention of participants
- Data collection
- Data management
- Behavioral coding from video
- Supervision of research assistants
- Making lab space warm, welcoming, and child and family friendly
- Quality control and ensuring high-quality and efficient procedures
- Attending and contributing at lab meeting

# Your Schedule {#schedule}

Here are the expectations regarding your schedule:

- You are in the office for your designated hours per week that are regularly scheduled between 9am–5pm Monday through Friday.
- You may have to work outside those hours (early mornings/evenings/weekends) for the purpose of running participants.
- You get approval from me for any deviations from this schedule (working outside those hours, working more than your designated hours, etc.), and update your schedule accordingly in the online calendar.
- You will log all hours worked using your Employee Self Service and submit them to the Lab Coordinator
- The position involves fully in-person work.
- You let me and the relevant team members know by Slack if you will not be able to make it in for your regularly scheduled hours.
- All information that is team relevant should be in Slack
- Personal communication (e.g., asking for time off) may be emailed
- You let me and the relevant team members know in person or by Slack if you are leaving the office (running lab errands, etc.).
- You keep your schedule in the online calendar up-to-date with any changes.
- You respond to team members promptly by email, Slack, or in person (within one business day).

# Priorities

These are a general order of priorities in the Dev-Psy Lab.
Dr. Petersen or the Lab Coordinator will inform staff if there are modifications to the priorities of tasks.

1.  If RAs are not available, be the E for LV1 visits
1.  Schedule families who have signed up via SignUpGenius
    -  Send reminders the night before the visit
1.  Check in once per week with pending scheduling contacts including: 
    -  Prospective participants who have indicated interest from the ICTS or Prospective Participants Survey for screening call
    -  Prospective participants who have been screened and are ready to be enrolled
    -  Enrolled participants ready to schedule for the next timepoint
1.  Send survey reminders once per week to:
    -  Primary caregivers who did not complete surveys during their visits
    -  Parenting partners
    -  Secondary caregivers
1.  Develop and refine new recruitment methods including: 
    -  Submitting monthly Peach Jar flyer
    -  Develop relationships with community organizations
    -  Flyering
1. Train LV1 Es
1.  Develop coding tasks 
1.  Schedule meetings with relevant team members including: 
    -  coding meetings
    -  trainings
    -  other meetings
1.  Miscellaneous office tasks
1.  Keep lab website up to date

# Expectations for Everyone in Lab {#expectationsForEveryone}

In addition to the expectations described above for lab staff, please also read the [expectations for everyone in the lab](expectations-everyone.html).

# Signature {#signature}

Please download, sign, and email the below document to Dr. Petersen prior to your first day in lab.

<embed src="Files/signature_page.pdf" width="1000" height="600">
