---
title: "Lab Wiki for the Developmental Psychopathology Lab"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  comment = "")
```

<u>Lab Contacts</u>

**Principal Investigator**\
[Dr. Isaac Petersen, Ph.D.](https://psychology.uiowa.edu/people/isaac-petersen)\
Office: 175 Psychological and Brain Sciences Building (PBSB)\
Email: isaac-t-petersen@uiowa.edu

**Lab Coordinator**\
[Giovanni Longino](https://developmental-psychopathology.lab.uiowa.edu/people/giovanni-longino-0)\
Office: 111 Spence Labs (SLP)\
Lab Email (preferred for lab-relevant communication): devpsy-lab@uiowa.edu\
Personal Email: giovanni-longino@uiowa.edu

**Lab Staff**\
[Laxmi Annapureddy B.S., B.A.](https://developmental-psychopathology.lab.uiowa.edu/people/laxmi-annapureddy)\
Office: 119 Spence Labs (SLP)\
Email: laxmi-annapureddy@uiowa.edu

[Johanna Caskey, B.A.](https://developmental-psychopathology.lab.uiowa.edu/people/johanna-caskey)\
Office: 119 Spence Labs (SLP)\
Email: johanna-caskey@uiowa.edu

**Graduate Students**\
[Jordan Harris, M.A.](https://developmental-psychopathology.lab.uiowa.edu/people/jordan-harris)\
Office: 109 Spence Labs (SLP)\
Email: jordan-l-harris@uiowa.edu

[Alexis Hosch, M.A.](https://developmental-psychopathology.lab.uiowa.edu/people/alexis-hosch)\
Office: 109 Spence Labs (SLP)\
Email: alexis-hosch@uiowa.edu

[Zachary Demko, B.A.](https://developmental-psychopathology.lab.uiowa.edu/people/zachary-demko)\
Office: 119 Spence Labs (SLP)\
Email: zachary-demko@uiowa.edu

**Location**:

Developmental Psychopathology Lab\
Spence Labs 109–119\
308 East Iowa Avenue\
University of Iowa\
Iowa City, IA 52242

**Website**: [https://developmental-psychopathology.lab.uiowa.edu](https://developmental-psychopathology.lab.uiowa.edu)\
**Social Media**:

- Facebook: https://www.facebook.com/DevPsyLab
- Twitter: https://twitter.com/devpsylab
- Instagram: https://instagram.com/dev_psy_lab
