---
title: "Open Science"
---

# Overview {#sec-overview}

We, as a lab, value and strive to advance the mission of [open science](https://onlinelibrary.wiley.com/doi/10.1002/icd.2315) to improve the accessibility, reproducibility, and replicability of science.
As such, all lab members are expected to conduct research transparently and to promote reproducibility.
This includes, but is not limited to, [pre- or co-registering](#sec-preregistration) studies, [sharing analysis scripts and data](#sec-sharing), using [version control](#sec-versionControl) (GitLab), submitting [preprints](https://psyarxiv.com) when submitting a manuscript to a journal, and providing support for other labs' attempts to replicate and reproduce our findings.
Our lab's template for projects on the [Open Science Framework](https://osf.io) (OSF) is located here[^1]: <https://osf.io/4w9sv>.

# Pre-Registration (or Co-Registration) {#sec-preregistration}

There is a continuum of registration approaches.
Pre-registration involves publicly posting aspects of a study (e.g., study design, hypotheses, methods, materials, and analysis plan) before data collection begins.
Co-registration involves specifying aspects of your study after data collection starts but before analysis.
Post-registration involves specifying aspects of your study after after analysis has begun.

Pre-registration is often considered the gold-standard.
However, co-registration and post-registration are better than no registration.

Here are elements of a study that can be registered:

- study design
- hypotheses
- methods
- materials
- analysis plan

When analysis decisions are contingent upon prior steps that may influence which decision to take, the analysis plan can include decision trees (e.g., if X, then Y; if A, then B).
For example, you can specify how you would proceed if the measures do not demonstrate longitudinal factorial invariance, or how you would handle poorly fitting models.

For templates of pre-registrations, see [here](https://help.osf.io/article/330-welcome-to-registrations#Select-a-Registration-Template-1g4YO) (archived at: <https://perma.cc/6DWT-YPXW>).
For guidance on selecting a template, see [here](https://www.cos.io/blog/choosing-preregistration-template-guide-for-researchers) (archived at: <https://perma.cc/773X-F9H4>).
When you have a pre-registration for a project, post it on one of the following services:

- [Open Science Framework](#sec-osf) (OSF)
    - either via their [registration platform](https://osf.io/registries/osf/new) or via a PDF of a Word document
- In the [GitHub](#sec-github) repository associated with the project
- [AsPredicted](https://aspredicted.org)
- [PROSPERO](https://www.crd.york.ac.uk/prospero) (for systematic reviews)
- [ClinicalTrials.gov](https://clinicaltrials.gov)

We most commonly post pre-registrations on the [OSF](#sec-osf).

# Sharing Data, Analysis Code, and Research Materials {#sec-sharing}

## Data {#sec-data}

When sharing data, make sure to share only <u>***deidentified***</u> data.
For any variables that have participant-identifying information, make sure to remove them from the data object before sharing.

To help protect participant anonymity, it is important to anonymize participant IDs so their data cannot be stitched together across papers.
To anonymize participant IDs, use the following script and change the seed for every paper so that a given participant gets a different anonymized code each time.

<https://devpsylab.github.io/DataAnalysis/openScience.html#sec-anonymizedID>

## Data Dictionary {#sec-dataDictionary}

For each study, we create a Data Dictionary.
A Data Dictionary is a metadata file that tells people the meaning of variables in the data file and how to interpret them.

For each paper project, we export a `.csv` file with the subset of the Data Dictionary variables used for that specific paper.
We upload that `.csv` file to the [GitHub](#sec-github) repository.

### Style Guide {#sec-styleGuide}

- Use Roboto font size 10
- Use an en dash (`–`; i.e., not a hyphen) to indicate a range:
    - e.g., 1–18 (not 1-18)
    - an en dash is technically correct; in addition, spreadsheets often read 3-7 as March 7th, but they correctly read 3–7

### Columns {#sec-columns}

The Data Dictionary should have the following columns:

- Variable Name
    - the variable name in the data file
- Form Name
    - the instrument or measure that the variable comes from
- Human-Readable Variable Name
    - a more easily readable version of the variable name
- Data Type
    - the format of the values in the column (e.g., string, binary, integer, numeric, date, time, etc.)
- Variable Type
    - whether the scale of measurement is nominal, ordinal, interval, or ratio
- Measurement Unit
    - the conceptual unit that is being measured (e.g., seconds, level, count)
- Allowed Values
    - the allowed values for a variable and (if possible), what conceptual level each value corresponds to (e.g., 0 = Male; 1 = Female)
- Description
    - conceptual description of the variable
- Definition
    - definitions of abbreviations, conceptual definitions of terms, mathematical definitions of how a variable is calculated, etc.
- Notes
    - additional notes about the variable and how it is calculated
- References
    - references for the measure and/or variable

#### Data Types {#sec-dataTypes}

Data Types include:

- string
    - include letters or other characters (and possibly numbers)
- factor
    - categorical variable with letters and/or numbers
- binary
    - 0/1
- integer
    - whole numbers (never decimals)
- numeric
    - numbers
- date
    - `MM/DD/YYYY`; e.g., 06/24/2020
- time
    - `HH:MM:SS` (e.g., 01:30:24), or `HH:MM` (e.g., 05:24), or `MM:SS`
- date-time
    - `MM/DD/YYYY HH:MM:SS` (e.g., 06/24/2020 01:30:24)

#### Variable Types {#sec-variableTypes}

Variable Types include:

- nominal
    - distinct categories
- ordinal
    - ordered categories
- interval
    - ordered with meaningful distances
- ratio
    - ordered with meaningful distances and an absolute zero

#### Measurement Units {#sec-measurementUnits}

Measurement Units include:

- ID
    - participant identification (ID) numbers
- count
    - number of something (e.g., number of children in the household)
- group
    - categories that reflect different groups (e.g., female vs male)
- instance
    - nominal categories that do not reflect groups
- yes/no
    - 0 = No; 1 = Yes
- ratio
    - ratio of two variables (one variable divided by another variable)
- USD
    - U.S. dollars ($)
- option
    - categories that reflect participant's choice among multiple options
- location
    - categories that reflect different locations
- state
    - categories that reflect a status
- degree
    - the degree of
- level
    - the level of
- grade
    - school grade
- date
    - `MM/DD/YYYY`; e.g., 06/24/2020
- time
    - `HH:MM:SS` (e.g., 01:30:24), or `HH:MM` (e.g., 05:24), or `MM:SS`
- date-time
    - `MM/DD/YYYY HH:MM:SS` (e.g., 06/24/2020 01:30:24)
- milliseconds
- seconds
- minutes
- hours
- days
- months
- years
- percentile
- item

### Analysis Code {#sec-analysisCode}

We can share analysis code for any text-based files, such as: 

- `R`: `.R`, `.qmd`, `.rmd`
- `Python`: `.py`, `.ipynb`
- `MATLAB`: `.m`
- `SPSS`: `.sps`

When sharing analysis code, where possible, it is helpful to share computational notebooks—i.e., analysis code in line with output.
That way, anyone can see what the output was of each line of code without having to run it themselves.
For instance, it can be helpful to share [Quarto](https://quarto.org) (`.qmd`) documents and the associated `.html` file with the output inline.
Our lab's template for Quarto documents is here[^1]: <https://research-git.uiowa.edu/PetersenLab/Template/-/blob/master/Analyses/quartoNotebook.qmd>.
Make sure the computational notebook does not include participant-identifying information as output.

### Research Materials {#sec-researchMaterials}

Where possible (e.g., when it does not violate copyright), we prefer to share research materials (e.g., stimuli, tasks, procedure manuals, coding manuals, etc.).

# Version Control {#sec-versionControl}

For projects involving human subjects data, we use the [UI Enterprise Instance of GitLab](https://research-git.uiowa.edu) for version control.
See our [lab's guide for using git/GitLab](https://devpsylab.github.io/DataAnalysis/git.html).
Our lab's template for GitLab repositories is located here[^1]: <https://research-git.uiowa.edu/PetersenLab/Template>.

# Preprint {#sec-preprint}

When submitting a manuscript to a journal, also submit a preprint to [PsyArXiv](https://psyarxiv.com).
Combine the supplemental material and manuscript into one PDF file when posting.
When submitting the manuscript to the journal, make sure to indicate in the cover letter that the manuscript was posted as a preprint, and provide the link to the preprint.

# Services {#sec-services}

## OSF {#sec-osf}

The [Open Science Framework](https://osf.io) (OSF) is a website for hosting [pre-registrations](#sec-preregistration)—and formerly data, analysis code, research-related materials, and preprints—to improve replicability and reproducibility of findings.
<!-- For each paper project, create a new repository on the OSF and add the relevant contributors, including Dr. Petersen. -->
Our lab's template for projects on the Open Science Framework (OSF) can be found here[^1]: <https://osf.io/4w9sv>.

### Create Anonymous View-Only Links for Anonymous Peer Review {#sec-anonymousViewOnlyLink}

With your project open, go to Settings (top-right) → View-Only Links → Add.
Then check "Anonymize".
Then you can share that URL.
For detailed instructions, see here: <https://help.osf.io/article/201-create-a-view-only-link-for-a-project> (archived at <https://perma.cc/AGJ9-V487>).

## GitHub {#sec-github}

GitHub is a website for hosting and sharing files, and can be used to share [pre-registrations](#sec-preregistration), (deidentified) [data](#sec-data), [analysis code](#sec-analysisCode), [research-related materials](#sec-researchMaterials), and [preprints](#sec-preprint) to improve replicability and reproducibility of findings.
For projects involving human subjects data, we use the [UI Enterprise Instance of GitLab](https://research-git.uiowa.edu) (not GitHub) for [version control](#sec-versionControl), as described in @sec-versionControl.
Then, for sharing (deidentified) [data](#sec-data) (and [data dictionary](#sec-dataDictionary)), [analysis code](#sec-analysisCode) (and computational notebooks), [research-related materials](#sec-researchMaterials), and [preprints](#sec-preprint), we use GitHub paired with [Zenodo](#sec-zenodo) (to obtain a persistent link via DOI).
That is, you will copy deidentified [data](#sec-data) and [analysis code](#sec-analysisCode) from the GitLab repository to a new GitHub repository (along with adding a [data dictionary](#sec-dataDictionary), other [research-related materials](#sec-researchMaterials), [preprints](#sec-preprint), etc.), for purposes of sharing.

For each paper project, create a new repository on GitHub and add the relevant contributors, including Dr. Petersen.
Our lab's template for projects on GitHub can be found here: <https://github.com/DevPsyLab/ZenodoTemplate>.
When we are ready to share the files (which may depend on whether the journal uses a blind review process), make the GitHub repository public and link the GitHub repository to [Zenodo](#sec-zenodo) to obtain a DOI, as described [here](#sec-zenodo).
The [Zenodo](#sec-zenodo) project for the lab's template project is here: <https://doi.org/10.5281/zenodo.22967623>.
Individual files in GitHub repositories cannot exceed 100 MB in size.

### Pre-Registration {#sec-githubPreregistration}

For information on posting a [pre-registration](#sec-preregistration), see [here](#sec-preregistration).

### Data {#sec-githubData}

For information on sharing [data](#sec-data), see [here](#sec-data).

### Data Dictionary {#sec-githubDataDictionary}

For information on creating and sharing a [data dictionary](#sec-dataDictionary), see [here](#sec-dataDictionary).
For each paper project, we export a `.csv` file with the subset of the [Data Dictionary](#sec-dataDictionary) variables used for that specific paper.
We upload that `.csv` file to the [GitHub](#sec-github) repository.
The formatting of the Data Dictionary is described [here](#sec-dataDictionary).

### Analysis Code {#sec-githubAnalysisCode}

For information on sharing [analysis code](#sec-analysisCode), see [here](#sec-analysisCode).

### Research Materials {#sec-githubResearchMaterials}

For information on sharing [research materials](#sec-researchMaterials), see [here](#sec-researchMaterials).

### Preprint {#sec-githubPreprint}

For information on sharing [preprints](#sec-researchMaterials), see [here](#sec-preprint).
A preprint can also be included in a [GitHub](#sec-github) repository.

## Zenodo {#sec-zenodo}

We use Zenodo to create a DOI for [GitHub](#sec-github) repositories.
For instructions how to share and preserve research materials and code via [GitHub](#sec-github) with a DOI, see here: <https://www.lib.uiowa.edu/data/share-and-preserve-your-code/> (archived at: <https://perma.cc/ND4B-W2JF>).
If you upload files manually to a Zenodo record (rather than via [GitHub](#sec-github) integration), Zenodo allows up to 100 files per record.
If you have more than 100 files, you can either put them in a zip file or can add them by connecting Zenodo to a [GitHub](#sec-github) repo.
Collectively, the files in a Zenodo record cannot exceed 50 GB.

# Manuscript Submission to a Journal {#sec-journal}

Before submitting a manuscript to a journal, make sure the [pre-registration](#sec-preregistration) is posted and make sure to post the relevant materials on a [GitHub](#sec-github), as described [here](#sec-github), and post the [preprint](#sec-preprint), as described [here](#sec-preprint).
When preparing a manuscript for submission to a journal, make sure to follow the Author Guidelines for each journal.
After finalizing the manuscript in accordance with journal guidelines and when you are ready to submit the paper to the journal (but before submission), post the [preprint](#sec-preprint) on [PsyArXiv](https://psyarxiv.com).
Include the link to the [preprint](#sec-preprint) in the cover letter to the journal.
In the Method section and on the title page, include the relevant links to the [pre-registration](#sec-preregistration), [data](#sec-data), [data dictionary](#sec-dataDictionary), [analysis code](#sec-analysisCode), computational notebook, and [research materials](#sec-researchMaterials), etc.
For example:

> Hypotheses and measures for the School Readiness Study were pre-registered: <https://osf.io/jzxb8>.
> Hypotheses methods, and a data analysis plan for the present study were also pre-registered: <https://osf.io/pny26>.
> Data files, a data dictionary, analysis scripts, and a computational notebook for the present study are published online: <https://osf.io/zs2bn>.

In the manuscript submission, create and use [anonymous view-only OSF links](#sec-anonymousViewOnlyLink) (for blind review).
In the [preprint](#sec-preprint) submission, use the general [OSF](#sec-osf)/[Zenodo](#sec-zenodo)/[GitHub](#sec-github) links (not the [anonymous view-only OSF links](#sec-anonymousViewOnlyLink)) that will become viewable when the manuscript is accepted for publication (i.e., when you make the OSF repository public).

# When the Manuscript is Accepted for Publication {#sec-accepted}

When the manuscript is accepted for publication:

1. Let all of the authors know, and send them the full, (in-press) APA-style reference
1. Make the [GitHub](#sec-github) repository public and link the repository to [Zenodo](#sec-zenodo) to [create a DOI link](https://www.lib.uiowa.edu/data/share-and-preserve-your-code/) (archived at: <https://perma.cc/ND4B-W2JF>) for the repository that can be used for citing it
1. Submit the finalized, unblinded manuscript (and any tables, figures, and the supplement; with the public [GitHub](#sec-github) link; removing any highlighting or tracked changes) to the NIHMS system: <https://www.nihms.nih.gov/submission/create/>
    - After you submit the manuscript to NIHMS, send Dr. Petersen the NIHMS ID for the submission.
    We are required to report published papers to funding agencies.
1. Make sure the finalized, unblinded manuscript (and any tables, figures, and the supplement; with the public [GitHub](#sec-github)/[Zenodo](#sec-zenodo) link; removing any highlighting or tracked changes) is uploaded as an updated version of the [preprint](#sec-preprint) on [PsyArXiv](https://psyarxiv.com).

# Adapting Open Science to Longitudinal Research {#sec-longitudinal}

See our paper on adapting open science to longitudinal research: <https://onlinelibrary.wiley.com/doi/10.1002/icd.2315>

[^1]: Ask Dr. Petersen to give you access.
