---
title: "Opportunities"
---

# Opportunities {#sec-opportunities}

Want to receive funding to conduct research as an undergraduate student?
The University of Iowa provides numerous funding opportunities via its research programs that support undergraduate students in conducting research.
For instance, you are encouraged to apply for research programs through the [Iowa Sciences Academy](https://isa.uiowa.edu/programs) and the [Office of Undergraduate Research](https://our.research.uiowa.edu/students/compensation-your-research).
The [Iowa Sciences Academy](https://isa.uiowa.edu/programs) and [Office of Undergraduate Research](https://our.research.uiowa.edu/students/compensation-your-research) have several opportunities that provide funding to help undergraduate research assistants work in a research lab, including:

- [Science Alliance Internship](https://isa.uiowa.edu/programs/sa)
- [UI-LSAMP Program](https://isa.uiowa.edu/programs/ui-lsamp)
- [UI-MARC Program](https://isa.uiowa.edu/programs/ui-marc)

If you are interested in pursuing a funding opportunity, please reach out to the Lab Coordinator and Dr. Petersen to discuss the application and funding requirements. 
If an opportunity requires an RA to work more than the required 10 hours per week, you can work with Dr. Petersen to set up expectations for additional lab hours and lab work.