---
title: "Application Guidelines for Prospective Graduate Students"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE,
  comment = "")
```

# Am I a good fit for the Psychological and Brain Sciences Ph.D. Program at the University of Iowa? {#fit-program}

The Psychological and Brain Sciences Ph.D. Program at the University of Iowa is a [<u>***research-focused***</u> training program](https://psychology.uiowa.edu/graduate).
Thus, our program is best aligned with careers in which research will be a key component.
We look to admit and train graduate students who have research-oriented career goals.
If you have career goals of being a clinician, our program would not be a good fit for you; you would not be happy here.

Given our research-focused training, applicants will be most competitive if they have strong research experiences.
What will make you most competitive for our program is having lots of high-quality research experience and showing evidence of capabilities to conduct independent research.
You will want to show evidence of independent research experiences, such as an Honors project, senior thesis, independent research project, first-authored publications in strong peer-reviewed journals, first-authored posters or presentations at strong national or international conferences, and grant/fellowship submissions—these are just examples (you are not expected to have all of these!).

# What graduate training tracks should I apply to in order to join the Developmental Psychopathology Lab? {#tracks}

Prospective graduate students interested in joining the lab can apply to <u>***any***</u> of the [graduate training tracks](https://psychology.uiowa.edu/graduate) of the Department:

- [Clinical Science](https://psychology.uiowa.edu/clinical-science)
- [Individualized Graduate Training Track](https://psychology.uiowa.edu/graduate/individualized-graduate-training)
- [Behavioral and Cognitive Neuroscience](https://psychology.uiowa.edu/research/behavioral-and-cognitive-neuroscience)
- [Cognition](https://psychology.uiowa.edu/cognition)

The [Individualized Graduate Training track](https://psychology.uiowa.edu/graduate/individualized-graduate-training) is an exciting training opportunity for students.
The [Individualized track](https://psychology.uiowa.edu/graduate/individualized-graduate-training) provides students considerable flexibility in their graduate training curriculum.
The [Individualized track](https://psychology.uiowa.edu/graduate/individualized-graduate-training) allows the student, in conjunction with their research committee, to custom-tailor their graduate training to meet their training goals.
Moreover, the [Individualized track](https://psychology.uiowa.edu/graduate/individualized-graduate-training) provides students more time for research than the [Clinical Science](https://psychology.uiowa.edu/clinical-science) track, because the [Individualized track](https://psychology.uiowa.edu/graduate/individualized-graduate-training) does not have clinical training requirements and has less coursework burden than the [Clinical Science](https://psychology.uiowa.edu/clinical-science) track.
In addition, the program generally receives more applications to the [Clinical Science](https://psychology.uiowa.edu/clinical-science) track than to the [Individualized track](https://psychology.uiowa.edu/graduate/individualized-graduate-training) (or to other tracks).
Thus, a person may be more likely to be admitted if they apply to the [Individualized track](https://psychology.uiowa.edu/graduate/individualized-graduate-training) or to another non-Clinical Science track.
However, regardless of the track(s) to which you apply, your application should clearly demonstrate the fit of your interests and experiences with the track(s) to which you apply.

In addition to a training track, students are welcome to join one of various departmental [research groups](https://psychology.uiowa.edu/research).
[Research groups](https://psychology.uiowa.edu/research) provide individualized, interdisciplinary, and student-centered research training in that domain.
Dr. Petersen is a member of the following [research groups](https://psychology.uiowa.edu/research):

- [Developmental Psychopathology](https://psychology.uiowa.edu/research/research-groups/developmental-psychopathology)
- [Developmental Science](https://psychology.uiowa.edu/developmental-science)
- [Cognitive Control](https://psychology.uiowa.edu/cognitive-control)

Students who are interested in joining the [Developmental Psychopathology Research Group](https://psychology.uiowa.edu/research/research-groups/developmental-psychopathology) and who do not want clinical training requirements are encouraged to apply to the [Individualized Graduate Training Track](https://psychology.uiowa.edu/graduate/individualized-graduate-training).

# Criteria used for evaluation of graduate applications {#application-criteria}

Your application will be reviewed closely by me and by the relevant training track.
So you have a sense of how graduate applications are evaluated, here are the criteria that I consider most strongly when evaluating applicants for graduate school and my lab:

- fit of interests with the Developmental Psychopathology Lab, including [the lab's current studies and focus](#currentFocus)
- fit of career goals with the mission of the program and the relevant training track
    - i.e., career goals in research
        - if you have goals of being a clinician, I would dissuade you from joining our program and this lab; you would not be happy here
- evidence of high-quality, independent research experience
    - e.g., Honors project, senior thesis, independent research project, first-authored publications in strong peer-reviewed journals, first-authored posters or presentations at strong national or international conferences, and grant/fellowship submissions—these are just examples (you are not expected to have all of these!)
- writing skills, especially in scientific writing
- quantitative/statistical skills
- academic preparedness for graduate school
- whether the trainee will not only meet, but will exceed the [lab expectations for graduate students](expectations-gradStudent.html)
  - for instance, my lab looks for students who will both benefit from—and contribute to—our team and the collaborative environment, and who will work regularly in the lab (i.e., during the workday, as described in the [lab expectations for graduate students](expectations-gradStudent.html)); we are not looking for "lone wolves"

In addition, successful applicants to my lab tend to have at least two years of research experience and to be involved in research when applying.

# The current focus of the Developmental Psychopathology Lab {#currentFocus}

The broader mission of the Developmental Psychopathology Lab is to advance understanding of how self-regulation develops so that we as a society can better treat or even prevent the development of externalizing problems.
That is, we are interested in identifiying *mechanisms* in the development of self-regulation and externalizing problems.

To this aim, the focal project of the lab's work is an ongoing NIH-funded longitudinal study, the [School Readiness Study](study-schoolReadinessStudy.html), that follows children from 3–7 years of age to better understand how self-regulation and externalizing problems develop, from a bio-psycho-social perspective.
In this project, we place special emphasis on the development of neural functioning, as measured by EEG/ERP, and how neural development influences the development of children's self-regulation and externalizing problems.
For more information on the study, you are encouraged to read papers from the project, view the available measures, examine the Data Dictionary, and see the pre-registered hypotheses.
These resources are available on the project page for the [School Readiness Study](study-schoolReadinessStudy.html).

Identifying mechanisms in the long-term development of externalizing problems requires strong assessment.
Thus, my lab is also highly interested in psychometrics and measure development.
In addition to the ongoing [School Readiness Study](study-schoolReadinessStudy.html), we are also in the process of designing and conducting another study, the [Externalizing Assessment Project](study-externalizingSpectrumAcrossLifespan).
Externalizing problems change in behavioral manifestation across development.
In this project, we aim to develop a novel assessment system to assess the externalizing spectrum in comparable and developmentally sensitive ways across the lifespan, so that we can identify children early on who are at risk of later, more severe problems.

Although the mechanisms we identify are relevant for intervention, my lab does not conduct research on interventions.

# Am I a good fit for the Developmental Psychopathology Lab? {#fit-lab}

Our program does not look for "mini-me"s whose interests are exactly the same as ours; at the same time, we do look for a core fit of research interests with the direction of the prospective lab(s) (which are described [above](#currentFocus)).
For instance, if your primary research interests are in any of the following domains, my lab would *not* be a good fit for your interests:

- depression/anxiety
- autism
- psychosis/schizophrenia
- trauma
- treatment/intervention

Different labs have different structures.
In some labs, graduate students conduct separate independent research projects.
My lab has a different structure.
We are conducting a large longitudinal project funded by the National Institutes of Health.
Work of this scope takes a village.
Thus, my lab's structure is "all hands on deck"—everyone (including research assistants, graduate students, lab staff, and me) contributes to the same large project.
This leads to a highly collaborative environment in which we can be more productive together.
Within the broader umbrella of our large longitudinal study, graduate students carve out their unique niche.
Graduate students in my lab lead projects that are part of the broader study.
As a result, to be a good fit for my lab, it is important that your interests align with our current study and work.
In general, I look for graduate students (a) who will "hit the ground running" in my lab, in terms of data analysis and writing papers, (b) whose interests closely align with the lab's current study and focus (as described [above](#currentFocus)), and (c) who will not only meet, but will exceed the [lab expectations for graduate students](expectations-gradStudent.html).
 
# What to do before applying {#before-applying}

Before applying, I encourage you to:

1. Read some of our [publications](https://developmental-psychopathology.lab.uiowa.edu/publications) to gain a sense of the type of work we do.
Especially relevant are the publications from our [current studies](#currentFocus).
1. Read the [lab expectations for graduate students](expectations-gradStudent.html) to make sure the lab would be a good fit for you.
1. Contact Dr. Petersen by email at isaac-t-petersen@uiowa.edu for more information about the lab; express your interests and send your CV to see if the lab would be a good fit for your interests.

# What to do when applying {#when-applying}

To make your application as strong as possible, I encourage you to:

1. Make sure your application—including your CV, professional statement, letters of recommendation, coursework, experiences, writing sample, etc.—addresses the above [criteria used for evaluation of applications](#application-criteria).
1. Include a writing sample in your application (separate from your professional statement).
It is preferable for the writing sample to be an example of scientific writing (e.g., APA-style manuscript), and for you to be the sole- or lead-author.
1. If there are weaknesses in your application (e.g., a period of poor grades, dropping out from a program) or things that merit explanation (e.g., if you are looking to switch programs/mentors), it is helpful for you to address them in your professional statement and to have your (relevant) letter writers address them in their letter.

# What to include in the Professional Statement as part of the application {#professional-statement}

I find it helpful when applicants include the following in their professional statements[^1]:

1. A clear statement of your general research interests and how they relate to our lab's mission and work
1. A clear statement of why you are interested in this lab, in particular, versus other labs that study the development of self-regulation and externalizing problems
1. A statement about your career goals (even if they are approximate/might change, it is helpful to see your thinking!), including the activities and context(s) of interest
1. Discussions of your independent research experience(s) and what you learned from them.
In these discussions, I suggest emphasizing (1) the skills you developed from working on each project (e.g., data collection; behavioral coding; statistical analysis; computer programming; neural or biopsychology methods such as EEG/ERP; software such as R, REDCap, MATLAB, E-Prime, and Datavyu; writing certain sections of a paper; submitting/presenting a poster), and (2) what your "takeaways" were from the project—e.g., new research ideas or questions your work inspired.

In addition, make sure to follow the Department instructions for the application and personal statement: https://psychology.uiowa.edu/graduate/admissions#step-3-submit-yourprogram-specific-materials

[^1]: This was borrowed from a [document](https://docs.google.com/document/d/1sQysBbb_dWhicWRlAUnRv-UWeJZgt-RmBxJPOfPIf9c/edit) by Prof. Jessica Schleider.
