---
title: "Application Guidelines for Prospective Undergraduate Research Assistants"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

We invite you to apply to join the Developmental Psychopathology Lab!

# About Being a Research Assistant in Our Lab

Research Assistant (RA) positions are available for credit or volunteering initially, but there may be opportunities for paid positions for RAs who have been in the laboratory for a while and demonstrated their commitment and interest.
Research assistants will gain experience with many lab procedures (e.g., collecting data during child lab visits, data management, and video coding of parent–child interactions).
There are also opportunities to complete honors theses for students who are interested and who have been in the lab for a while.
Positions in our laboratory may be particularly interesting and greatly beneficial for those who plan to enter graduate programs in clinical psychology or developmental psychology.
Experience with young children is highly desirable.
Completion of introductory courses in research methods and statistics is desirable but not required.
Expectations for undergraduate RAs are described [here](https://devpsylab.github.io/LabWiki/expectations-undergradRA.html).

# How Long Should I Plan to Stay in Lab?

Given the extensive amount of training involved in our lab, RAs are expected to make a commitment to work in the lab for *at least* two semesters for three credit hours (9 hours/week of working in lab, plus 1 hour weekly lab meeting) each semester.
That said, we are especially interested in prospective RAs who are interested in working in the lab for much longer than that.
The longer the RA stays in lab, the more opportunities become available to them in terms of advanced training, advancement, leadership, and independent research projects (e.g., Honors theses) that can help them be competitive for graduate/professional school and jobs.
To take on a more advanced training role, RAs are expected to commit to at least three semesters.

# How Do I Apply?

To apply, please submit the following application: [Undergrad Research Assistant Application](https://uiowa.qualtrics.com/SE/?SID=SV_6foZRkaDKfsPf49)

# Questions

If you have questions, please contact the Developmental Psychopathology Lab at: devpsy-lab@uiowa.edu.
