---
title: "Video Editing"
---

# Avidemux {#avidemux}

## General Video Editing {#generalVideoEditing}

- Search the computer for the *Avidemux* program.
- <u> To combine videos: </u>
   1. Open first video that you want to merge (*File* > *Open* > Find file on lab drive).
   1. Save the first video clip
   1. Repeat steps 1 and 2, naming them numerically (clip2, clip3, etc.) in the order you want the videos to be combined.
   1. Click the "Convert.bat" file in the *Video converter* folder. This will convert all clips to the same frame size and automatically move them to the *"Converted"* folder.
   1. Delete the video clips from the *Toconvert* folder.
   1. Go to *Avidemux* and clear program workspace (File > Close).
   1. Open the desired clip as the first clip of the video (Clip1) from the *Converted* folder.
   1. Once the first video is open, go to "File", click "Append", then select the next clip to be added. Continue this process until they have all been added, in the order you want them to be in the finished video. 
   1. Once a full compilation video is completed, go to "File", click "Save"
      - Name the video accordingly 
   1. Delete the video clips from the *Converted* folder
- <u> To clip videos: </u>
   1. Open the video you want to clip (*File* > *Open* > Find file on lab drive). 
   1. On the bottom left-hand side of the window, drag the blue tab on the video duration bar to the desired start time then press the *A* button to set it.
   1. Once the clip start time is selected, again drag the same blue tab on the duration bar to the desired end time then press the *B* button to set it.
   1. Once the accurate clip time window is selected, go to "File", click "Save" 
      - Name the clip accordingly 
   1. Go to *Avidemux* and clear program workspace (File > Close).
   1. Repeat steps 1-5 until you have created all the clips needed.
   
## Combining Videos {#combiningVideos}

### Stitching Two Videos Together Side-By-Side {#sideBySideVideos}

LV1 videos should be a side-by-side combination of recordings from Cameras 1 and 2 in the LV1 Experimenter Room.
The Observation Room computer has been set up to combine these recordings into one video file when it saves.
In the event that they save separately and result in two separate video files of the full visit, they can be knit together as one side-by-side video by following these steps:

1. Move the video files to be combined to the folder "Side by Side," found here: `\\lc-rs-store24.hpc.uiowa.edu\lss_itpetersen\Lab\Studies\School Readiness Study\Videos\01-Admin\Side by side\`
1. Click the "Convert.bat" file in the same folder
1. Enter the name of the video file you want displayed on the left side of the combined video (Camera 1 angle), then press the Enter key on the keyboard
    a. NOTE: You enter the entire file name, including the extension (e.g., `1001video1.mp4`)
1. Enter the name of the video file you want displayed on the right side of the combined video (Camera 2 angle), then press the Enter key on the keyboard
    a. NOTE: You enter the entire file name, including the extension (e.g., `1001video2.mp4`)
1. If the file is large, the program may take over an hour to combine, but do not close out of the window until it has finished running.
When it is done, there will be a saved video file named "Combined.mp4" in the same folder.
1. Rename the "Combined.mp4" file with `TCID_Wave_LV1` and move it to the TC's LV1 video folder on the drive (`\\lc-rs-store24.hpc.uiowa.edu\lss_itpetersen\Lab\Studies\School Readiness Study\Videos\Lab Visit 1\`)

NOTE: This script will only work if you open the Lab Drive directly from the Desktop to navigate to the Side by Side folder.
*You cannot open it from the Quick Access menu in File Explorer.*

An alternative approach is to use [ffmpeg](https://ffmpeg.org) (https://unix.stackexchange.com/a/437044; archived at: https://perma.cc/DWR8-4LST).
Using Command Prompt (`cmd.exe`), use the following syntax when in the target directory (use `cd DIRECTORY` to navigate to the target directory):

```bash
ffmpeg -i left.mp4 -i right.mp4 -filter_complex hstack output.mp4
```

### Stitching Two Videos Together One After The Other {#stitchingVideosOneAfterOther}

In the event that an LV1 video recorded side-by-side but the video was interrupted, resulting in two separate side-by-side video files that stop and start in the middle of a visit (e.g., if the camera box is accidentally kicked off during a visit, if the cameras crash and have to be restarted during the visit, etc.), they can be combined into one video file using Avidemux.
See the "Cute Moments Videos" section of the School Readiness Wiki for a description of how to use this program.
To combine two videos from a visit with interrupted recordings, follow these steps:

1. Open the computer program Avidemux
1. Open the first visit video for a given TC (File &rarr; Open &rarr; Find files on lab drive)
1. Open File Explorer and locate the video files
1. Drag the second video from the File Explorer Window straight into the Avidemux window, dropping it over the first video—you should see the video duration increase when it is added, indicating it is appending to the end of the previous video
1. Save the new video in the TC's folder as TCID_Wave_LV1 (`\\lc-rs-store24.hpc.uiowa.edu\lss_itpetersen\Lab\Studies\School Readiness Study\Videos\Lab Visit 1\`)

An alternative approach is to use [ffmpeg](https://ffmpeg.org) (https://ma.ttias.be/use-ffmpeg-combine-multiple-videos/; archived at: https://perma.cc/F9P9-KS4D):

First, using Command Prompt (`cmd.exe`), create a text file named `files.txt` in the same directory as the videos you want to combine (use `cd DIRECTORY` to navigate to the target directory) with the following content:

```bash
cat files.txt
file 'file 1.mp4'
file 'file 2.mp4'
file 'file 3.mp4'
file 'file 4.mp4'
```

Then, run the following command in the Command Prompt to combine the videos listed in `files.txt` into a single output file named `output.mp4`:

```bash
ffmpeg -f concat -safe 0 -i files.txt -c copy output.mp4
```

# Handbrake {#handbrake}

## Cutting and Creating Clips {#cuttingAndCreatingClips}

When a video requires cutting and subsequent clips must be created, the software, Handbrake, should be utilized.
Handbrake allows for easy creation of video clips in .mp4 format from a source video in the .mp4 format.
<br>

*Note:* Handbrake does not allow for it's user to scrub through the video within the software.
Thus, the needed timestamps for the start and end of the desired clip must be determined before uploading the video into Handbrake.
These timestamps will then be entered into Handbrake to create the clip.
<br>

To create video clips in Handbrake, complete the following steps:

1. Open Handbrake
1. On the left side of the screen under the tab titled, "Source Selection," select `File`
1. Select the video which requires cutting from its location in the lab drive.
The video should now be present in the display and open to editing
1. Within the main display, locate the "**Range:**" tab.
Change the selected option from `Chapters` to `Seconds` from the drop-down menu
1. To the right of the "**Range:**" tab, enter your desired start and end timestamps for the clip within the time input boxes.
The start and end timestamps for the desired clip should be determined before uploading the video into Handbrake
1. In the middle of the Handbrake display, under the "Summary" tab, ensure that the "**Format:**" is selected to `MP4`.
`MP4` should automatically be selected, however, if it is not, manually select `MP4` from the drop-down menu
1. At the bottom of the screen, next to the "**Save As:**" title, click the `Browse` button in order to select the desired folder from the lab drive in which to save the created clip.
Additionally, edit the name of the clip to be as needed by altering the name after the final backslash of the selected filepath.
Also verify that the name ends in `.mp4`
1. After selecting the save location for the video, at the top of the Handbrake display, select the large green play button titled, `Start Encode`, in order to create the clip
1. Upon completion of encoding, view the created video in order to ensure the clip was successfully made with desired start and end times

### Creating Multiple Clips from the Same Video Simultaneously {#creatingMultipleClips}

Multiple clips can be made from the same source video and processed simultaneously in Handbrake.
<br>

To create multiple clips from the same video simulatneously, complete the following steps:

1. Open Handbrake
1. On the left side of the screen under the tab titled, "Source Selection," select `File`
1. Select the video which requires cutting from its location in the lab drive.
The video should now be present in the display and open to editing
1. Within the main display, locate the "**Range:**" tab.
Change the selected option from `Chapters` to `Seconds` from the drop-down menu
1. To the right of the "**Range:**" tab, enter your desired start and end timestamps for the first clip to be made within the time input boxes.
The start and end timestamps for the desired clip should be determined before uploading the video into Handbrake
1. In the middle of the Handbrake display, under the "Summary" tab, ensure that the "**Format:**" is selected to `MP4`.
`MP4` should automatically be selected, however, if it is not, manually select `MP4` from the drop-down menu
1. At the bottom of the screen, next to the "**Save As:**" title, click the `Browse` button in order to select the desired folder from the lab drive in which to save the created clip.
Additionally, edit the name of the clip to be as needed by altering the name after the final backslash of the selected filepath.
Also verify that the name ends in `.mp4`
1. After selecting the save location for the video, at the top of the Handbrake display, select the `Add to Queue` button in order to add the clip to the queue
1. Repeat steps 4-7 for each clip to be made from the source video.
Ensure the start and end times are changed appropriately for each clip and the file name for each of the clips is changed and named appropriately
1. Once all clips desired to be made have been added to the queue, select the large green play button titled, `Start Queue`, in order to create all the clips listed within the queue
1. Upon completion of encoding, view the created videos in order to ensure the clips were saved to the correct file location(s) and each clip was successfully made with desired start and end times

# Converting Media Files to .mp4 {#convertToMp4}

To convert video of alternate file type to .mp4, complete the following steps:

1. Open VLC Media Player
1. In the top left corner, select "Media" and then navigate downwards to select "Convert / Save..."
1. Under "File selection," click the "+Add" button to add the files needing conversion.
Multiple files can be selected at a time
1. Click the drop-down arrow under "Convert / Save" at the bottom of the window and select "Convert"
1. Under the "Settings" heading, for the "Profile" select `Video - MPEG-2 + MPGA(TS)`.
Then, click on the wrench icon to the right and under "Encapsulation" select the `MP4/MOV` radio button.
Select "Save"
1. Under "Destination File," browse to map where the converted .mp4 file should be saved
   - *Note:* If multiple files are being converted, "Destination File" cannot be altered, and the files will automatically be saved to the same location from which they are being pulled
1. Click start to begin converting to .mp4
